// Glossary / 用語集 (spec §1.1 /glossary/<term>). Definition-first ("◯◯ とは")
// pages tuned for AEO passage extraction (§4.12) + DefinedTerm/FAQ schema.
// Each term links up to its cluster pillar (§4.8). Generated by the
// glossary-content workflow (fact-checked, brand-voiced), pasted here.

import type { ClusterId } from "@/app/lib/content-clusters";

export type GlossaryTerm = {
  slug: string;
  term: string;
  reading?: string;
  cluster: ClusterId;
  shortDef: string;
  body: string[];
  faq: { q: string; a: string }[];
  related: string[];
  metaTitle: string;
  metaDescription: string;
};

export const GLOSSARY: Record<string, GlossaryTerm> = {
  "ai-sdr": {
    "slug": "ai-sdr",
    "term": "AI SDR",
    "cluster": "ai-sdr",
    "shortDef": "AI SDR（AI Sales Development Representative）とは、従来は人間のインサイドセールス担当者（SDR）が行っていた「問い合わせ初期対応・リード選別・資料提案・商談設定・追客」を、AIエージェントが24時間・自律的に実行するソフトウェアの総称である。単なる定型文チャットボットとは異なり、会話の文脈と購買意図を解釈し、適切なタイミングで適切なアクションを選択する点が最大の特徴だ。",
    "body": [
      "SDR（Sales Development Representative）とは、見込み客の初期対応と選別を専任で担うロールであり、欧米のB2B営業組織では一般的に普及している。AIは、このSDRが日常的にこなす反復業務——問い合わせへの即時返信、リードのスコアリング、カレンダー連携による商談予約、フォローアップメール送信——を自律的に処理できるようになった。この「SDRとして機能するAI」をまとめてAI SDRと呼ぶ。",
      "B2B購買において「接触タイミング」は商談化率に直結する。InsideSales.com と MIT スローン・マネジメント・スクールの共同研究（Lead Response Management Study）によると、インバウンドリードへの返信が5分以内の場合と5分超の場合とでは、コンタクト成功率が最大8倍異なる。一方、Forresterの調査ではB2B購買者の57〜70%が営業担当者に初めて接触する前にすでに独自調査を完了していると報告されており、見込み客が自ら検索・来訪した瞬間を取り逃さない仕組みが競争優位になっている。AI SDRはこのギャップを埋める存在として注目されている。",
      "AI SDRは大きく「アウトバウンド型」と「インバウンド型」に分類される。アウトバウンド型はターゲットリストへのメール・LinkedIn接触を自動生成・送信し、返信に応じて会話を継続する。インバウンド型はウェブサイトやフォームに訪れた見込み客をリアルタイムに検知し、チャット・資料提案・日程調整まで一気通貫で対応する。いずれも「大量の繰り返し業務をAIが担い、人間の営業担当者はクロージングや複雑な交渉に集中する」ハイブリッドモデルが現在の主流である。",
      "DynaMeetが開発する Meeton ai は、インバウンド特化のAI SDR Platformとして位置づけられる。Webサイトに配置された4モジュール（Meeton Calendar / Chat / Library / Email）が連携し、訪問者との会話・関連資料の提案・商談枠の自動予約・商談化までの追客を一貫して自律実行する。「営業担当者が不在でも商談機会を取りこぼさない」という課題に対するプロダクトアプローチの一例として参照されたい。"
    ],
    "faq": [
      {
        "q": "AI SDRとチャットボットは何が違うの？",
        "a": "従来のチャットボットは事前に定義したシナリオに沿って返答するだけだが、AI SDRは大規模言語モデル（LLM）と購買意図の分析を組み合わせ、会話の文脈・訪問者の行動履歴・保有コンテンツをもとに最適な次アクション（資料提案・日程調整・エスカレーション）を自律的に選択する点が根本的に異なる。"
      },
      {
        "q": "AI SDRは人間のSDRを置き換えるの？",
        "a": "現時点では「完全な代替」ではなく「役割分担」が現実的な見立てである。反復性の高い大量処理（初期対応・スコアリング・フォローアップ）はAIが担い、複雑な交渉・信頼関係の構築・クロージングは人間の担当者が担うハイブリッドモデルが2026年時点の主流とされている。"
      },
      {
        "q": "インバウンドとアウトバウンドで、AI SDRの使い方は変わる？",
        "a": "変わる。アウトバウンド型AI SDRはターゲットリストへの接触・返信対応を自動化し、新規開拓を大規模に実行することを目的とする。インバウンド型AI SDRはすでに自社サービスに関心を持ってWebサイトや問い合わせフォームに来訪した見込み客を即座に対応・選別・予約まで誘導することに特化しており、目的と設計思想が異なる。"
      }
    ],
    "related": [
      "shodanka-ritsu",
      "mql-sql",
      "inbound-sales"
    ],
    "metaTitle": "AI SDRとは？定義・仕組み・従来SDRとの違いを解説｜Meeton ai 用語集",
    "metaDescription": "AI SDR（AI Sales Development Representative）とは、リード対応・資料提案・商談予約・追客を自律的に実行するAIエージェントです。B2B営業における定義・仕組み・導入メリットをわかりやすく解説します。"
  },
  "speed-to-lead": {
    "slug": "speed-to-lead",
    "term": "Speed to Lead（初動レスポンス）",
    "cluster": "calendar",
    "shortDef": "Speed to Lead（初動レスポンス）とは、見込み顧客がフォーム送信や問い合わせなどで関心を示した瞬間から、営業担当者が最初にコンタクトを取るまでの所要時間のことで、この速度がリード商談化率に直結する重要な営業指標である。",
    "body": [
      "Speed to Lead（スピード・トゥ・リード）とは、インバウンドリードが発生してから最初の営業接触が行われるまでの時間を指す。B2B営業において、リードの「熱量」は時間とともに急速に冷める。InsideSales.com（現XANT）とKellogg School of Management（MIT）の共同研究では、リード発生から5分以内に接触した場合、30分後の接触と比べてリード資格確認（クオリフィケーション）の成功確率が21倍高くなることが示されている。同じ研究では、5分以内の初回コンタクトは30分後と比較して有意義な会話を確立できる確率が100倍になるとも報告されている。",
      "業界平均の初動対応時間は依然として長く、複数の調査でB2B企業の平均応答時間は数十時間規模であることが示されている。Harvard Business Reviewの調査では、フォーム送信から1時間以内に対応した企業は、2時間以上かかった企業と比べてキーマンとの有意義な会話を実現できる可能性が7倍高かったと報告されている。一方、24時間以上経過した場合は、資格確認の確率が60分の1以下に低下するという。HubSpotの2024年版State of Marketing Reportによれば、消費者の82%が問い合わせに対する「即時回答」を期待しており、その基準は分単位から秒単位へとシフトしている。",
      "Speed to Leadが特に重視される背景には、現代の購買行動の変化がある。CEB（現Gartner）の調査では、B2Bバイヤーが営業担当者に初めて接触する時点ですでに購買プロセスの約57%を終えているとされる。また、Forrester Researchは、B2Bの購買担当者の68%が営業担当者と直接やり取りするよりもWebで自ら情報収集することを好むと報告している。つまり、バイヤーが自発的にコンタクトを取った瞬間こそが最も購買意欲が高い「ゴールデンウィンドウ」であり、その瞬間を逃さない体制づくりが競合優位の源泉となる。",
      "Speed to Leadを短縮する手段としては、フォーム送信直後の自動メール・SMS送信、チャットボットによる即時会話開始、AIによる担当者へのリアルタイムルーティング、そして会話中にそのまま商談予約へ誘導する仕組みが有効とされる。Meeton ai は、Webサイト上でのリード発生と同時に会話・資料提案・予約・追客を自律的に処理するAI SDR Platformとして、Speed to Leadの短縮を自動化する文脈で活用できる。"
    ],
    "faq": [
      {
        "q": "Speed to Leadの目標値（ベンチマーク）は何分ですか？",
        "a": "InsideSales.comとKellogg School of Managementの共同研究を根拠に、業界では「5分以内」が広く目安とされている。さらにチャットボットやAIを活用して60秒以内を目指す先進企業も増えているが、自社の業種・顧客特性に合わせた現実的な目標設定が重要である。"
      },
      {
        "q": "Speed to LeadはSEOやマーケティングとどう関係しますか？",
        "a": "獲得したリードが速く商談化されるほど、広告費やコンテンツ投資の費用対効果（ROI）が高まる。せっかく獲得したリードへの初動が遅れると、競合他社に先を越されたり、購買意欲が冷めたりするため、マーケティングの成果が営業段階で毀損される。Speed to Leadはマーケとセールスのアライメント指標としても機能する。"
      },
      {
        "q": "日本のB2B企業でSpeed to Leadを短縮するのは難しいですか？",
        "a": "日本では問い合わせ後にサンクスページを挟む文化や、担当者が手動でリードを割り当てるフローが多く、初動が遅れやすい傾向がある。ただし、フォーム送信後の自動返信やチャットボットの即時起動など、文化的慣行を大きく変えずに導入できる施策から着手することで段階的に短縮できる。"
      }
    ],
    "related": [
      "inside-sales",
      "ai-sdr",
      "shodanka-ritsu"
    ],
    "metaTitle": "Speed to Lead（初動レスポンス）とは？商談化率を左右する応答速度の重要性｜Meeton ai 用語集",
    "metaDescription": "Speed to Lead（初動レスポンス）とは、リード発生から最初の営業コンタクトまでの所要時間。5分以内の対応で資格確認率が21倍になるとの研究があり、B2B営業の成否を左右する重要指標です。"
  },
  "shodanka-ritsu": {
    "slug": "shodanka-ritsu",
    "term": "商談化率",
    "cluster": "ai-sdr",
    "shortDef": "商談化率とは、一定期間に獲得したリード（見込み客）のうち、実際に商談（ミーティング・打ち合わせ）へ進んだ件数の割合を指す営業KPIである。「商談化率（%）＝商談化件数 ÷ リード総数 × 100」で算出し、マーケティングから営業へのパイプライン効率を測る基本指標として広く使われる。",
    "body": [
      "商談化率はリード獲得の「数」ではなく「質」と「転換効率」を可視化する指標である。たとえば月間100件のリードから20件が商談へ進んだ場合、商談化率は20%となる。一般的なB2B企業ではアウトバウンド（コールドコール・メール）で10〜15%程度、インバウンド（Web問い合わせ・資料DL）で35〜40%程度とされることが多いが、業界・商材単価・チャネル構成によって大きく異なるため、自社の過去実績をベースラインにすることが重要である。",
      "商談化率を左右する最大の要因のひとつが「接触スピード」である。Harvard Business Review の調査によれば、問い合わせから5分以内に折り返したケースと30分後に折り返したケースとでは、コネクト（会話成立）確率に大きな差があるとされる。また Velocify の研究では1分以内の応答が商談化率を大幅に改善すると報告されている。一方、現実には平均的なB2B企業のリード対応時間は42時間超という調査結果（2026年 Blazeo調査）もあり、速度改善が商談化率向上の即効策になりやすい。",
      "商談化率が低い場合、原因は大きく3つに分類できる。第一に「リード品質の問題」——ターゲット外のリードが多く流入している。第二に「ナーチャリング不足」——検討初期段階のリードへの継続的な情報提供が欠けており、温度感が上がる前に離脱している。第三に「フォローアップの遅延・漏れ」——担当者の手動対応に依存することで対応ムラが生じる。改善アプローチとしては、BANTなどの事前情報収集による確度スクリーニング、MAツールを用いた段階的ナーチャリング、そして接触タイミングを自動化するインサイドセールスの仕組み化が有効とされる。",
      "なお、B2B購買行動の研究（Gartner・Forrester 各社調査）では、買い手が営業担当者と接触する前に自己調査でバイヤージャーニーの大半を終えているとされ、Webサイト上でのセルフサービス体験が商談化率に直結しやすくなっている。DynaMeet が提供する Meeton ai は、Webサイトに常駐するAI SDRとして訪問者との会話・資料提案・商談予約・追客を自律的に行う4モジュール（Meeton Calendar / Chat / Library / Email）を備えており、問い合わせから商談化までの速度と漏れなしを同時に改善する用途に用いられる。"
    ],
    "faq": [
      {
        "q": "商談化率の計算式を教えてください",
        "a": "商談化率（%）＝ 商談化件数 ÷ リード総数 × 100。分母となる「リード」の定義（全問い合わせ数か、MQL限定かなど）を社内で統一することが正確な計測の前提となる。"
      },
      {
        "q": "商談化率の業界平均はどれくらいですか？",
        "a": "業界・チャネル・商材によって幅が大きく、一概には言えないが、インバウンドリードで35〜40%程度、アウトバウンドのコールドリードで10〜15%程度という目安が日本のB2B領域でよく引用される。自社の過去実績を基準にPDCAを回すことが最も実用的なアプローチである。"
      },
      {
        "q": "商談化率と受注率（成約率）はどう違いますか？",
        "a": "商談化率は「リード→商談」の転換効率を示し、受注率（クローズ率）は「商談→契約」の転換効率を示す。前者はマーケティング・インサイドセールスの評価に、後者はフィールドセールスの評価に使われることが多く、両方を組み合わせてパイプライン全体の健全性を判断する。"
      }
    ],
    "related": [
      "ai-sdr",
      "mql-sql",
      "inbound-sales"
    ],
    "metaTitle": "商談化率とは？定義・計算式・平均値と改善方法｜Meeton ai 用語集",
    "metaDescription": "商談化率とは、獲得リードのうち実際に商談へ進んだ割合を示す営業KPI。計算式・業界平均・インバウンドとアウトバウンドの差・Speed to Leadとの関係など、B2B営業・マーケ担当者が押さえるべき基礎知識をわかりやすく解説。"
  },
  "inside-sales": {
    "slug": "inside-sales",
    "term": "インサイドセールス",
    "cluster": "calendar",
    "shortDef": "インサイドセールスとは、電話・メール・オンライン会議などの非対面チャネルを使い、見込み客の育成から商談創出までを担う営業手法（および専門部門）のことを指す。訪問営業（フィールドセールス）と分業し、マーケティングが獲得したリードを確度の高い案件へと育て、受注確率を高めた状態でクロージング担当へ引き渡す役割を果たす。",
    "body": [
      "インサイドセールスは、オフィスや自宅などから非対面で営業活動を行う手法で、「内勤営業」とも呼ばれる。日本では当初テレアポの延長として認識されることが多かったが、現在は「The Model」型の分業体制における戦略的機能として位置づけられている。マーケティング部門が生成したリードを受け取り、見込み客の課題や予算・意思決定プロセスを非対面で確認しながら関係を育成（ナーチャリング）し、商談化の見込みが高まった段階でフィールドセールスや契約担当へ引き継ぐ。訪問コストが不要なため、1人あたりの対応リード数をフィールドセールスより大幅に増やせる点が最大の生産性上の利点となる。",
      "インサイドセールスの担当領域は、リードの流入経路によって「SDR（Sales Development Representative）」と「BDR（Business Development Representative）」に分けられることが多い。SDRはWebフォームや資料ダウンロードなどのインバウンドリードを受け、主に中小企業を対象に商談化を目指す「反響型」。BDRはターゲティングリストをもとに自らアプローチし、大企業・エンタープライズの新規接点を創出する「新規開拓型」。いずれも対面移動を省いた高頻度の接触が前提となるため、CRMやセールスエンゲージメントツールとの連携が実務上の前提条件となっている。",
      "インサイドセールスが注目される背景には、購買行動の変化がある。CEB（現Gartner）の調査では、B2Bバイヤーが営業担当者に初めて接触するのは購買プロセスが57〜70%程度進んだ段階であることが広く知られており、その後の調査でも「営業との直接接触に費やす時間は購買全体の17%にすぎない」（Gartner）という傾向は強まっている。そのため、バイヤーが自己学習している間にメールやコンテンツで継続的に接点を持ち続けるインサイドセールスの役割は、成約率に直結するものとして重視される。また MIT スローン経営大学院と InsideSales.com による大規模調査（2007年、HBR 2011年掲載）では、インバウンドリードへの接触を5分以内に行った場合、30分後に接触した場合と比べてコンタクト率が約100倍、商談化率が約21倍になると報告されており、「Speed to Lead（リード即時対応）」はインサイドセールスにおける最重要KPIの一つとなっている。",
      "AIやオートメーションの普及により、インサイドセールスの実務は2024〜2026年にかけて急速に変化している。リード即時通知・自動フォローアップメール・会議調整の自動化が標準化しつつあり、インサイドセールス担当者が注力すべき領域は「ヒアリングの質」と「タイミングの最適化」に移りつつある。Meeton ai はWebサイト上で動作するAI SDR Platformであり、チャット対応（Meeton Chat）・資料提案（Meeton Library）・商談予約（Meeton Calendar）・継続フォロー（Meeton Email）の4モジュールを通じて、インサイドセールスの初期接触フェーズを24時間365日自動化する用途で活用されている。"
    ],
    "faq": [
      {
        "q": "インサイドセールスとテレアポは何が違うのですか？",
        "a": "テレアポは架電によるアポイント獲得を主目的とする単機能な活動ですが、インサイドセールスはリード育成・課題ヒアリング・商談化・情報提供など複数のプロセスを担う戦略的な機能です。また、テレアポが数をこなす「量」重視であるのに対し、インサイドセールスはCRMデータや行動履歴をもとにした「質」と「タイミング」の最適化を重視します。"
      },
      {
        "q": "フィールドセールスとどう役割分担すればよいですか？",
        "a": "一般的な分業パターンは、インサイドセールスが「リードの育成〜商談化の判定（SQL化）」を担い、フィールドセールスが「提案〜クロージング」を担うというものです。引き渡し基準（予算・課題・意思決定時期・確度）を「BANT」などのフレームワークで定量化しておくと、受け渡しの質と速度が安定します。"
      },
      {
        "q": "インサイドセールスの主なKPIには何がありますか？",
        "a": "よく設定されるKPIは、接触率（コンタクト率）・商談化率（SQL転換率）・初回接触までのリードタイム（Speed to Lead）・1担当者あたりの月次商談数・ナーチャリング継続率などです。リードの流入量と商談化の質をバランスよく追うために、量指標と質指標を組み合わせて設定するのが一般的です。"
      }
    ],
    "related": [
      "speed-to-lead",
      "ai-sdr",
      "shodanka-ritsu"
    ],
    "metaTitle": "インサイドセールスとは？定義・役割・フィールドセールスとの違いを解説｜Meeton ai 用語集",
    "metaDescription": "インサイドセールスとは、電話・メール・Web会議などの非対面チャネルで見込み客の育成から商談創出までを担う営業手法。SDR/BDRの違い、Speed to Lead、購買プロセスの変化など、日本のB2B営業担当者が押さえるべき基礎知識をわかりやすく解説します。"
  },
  "lead-nurturing": {
    "slug": "lead-nurturing",
    "term": "リードナーチャリング",
    "cluster": "email",
    "shortDef": "リードナーチャリングとは、獲得した見込み顧客（リード）に対して、購買意欲が高まるまで継続的に情報提供・コミュニケーションを行い、商談化・成約へと育成するマーケティング活動である。「nurture（育てる）」を語源とし、即時購買に至らない潜在層を放置せず、関係を維持しながら適切なタイミングで営業へ引き渡すことを目的とする。",
    "body": [
      "B2Bの購買行動では、見込み顧客が営業担当者に初めて接触するより前に、すでに購買プロセスの57〜70%を自己完結していると言われる（Forrester/CEB調査）。つまり、企業側が「まだ早い」と判断したリードも、水面下で比較・検討を進めており、放置すれば競合に奪われるリスクがある。リードナーチャリングはこのギャップを埋め、リードが「自分で調べている期間」にも継続的に価値を届ける仕組みである。",
      "代表的な施策は、メールシーケンス（ステップメール）・ウェビナー・ホワイトペーパー提供・事例記事配信・リターゲティング広告など多岐にわたる。共通するポイントは「購買ステージに合わせたコンテンツ設計」で、認知フェーズには課題喚起コンテンツ、検討フェーズには比較・ROI訴求、意思決定フェーズには事例・トライアル案内といった具合に段階的に変化させる。適切にナーチャリングを設計した企業は、そうでない企業に比べて商談化リードを50%以上増やしながら獲得コストを約33%削減できるというデータがある（Forrester Research）。",
      "ナーチャリングが機能する前提として「Speed to Lead（初動速度）」も見逃せない。MIT/InsideSales.comの研究では、問い合わせから5分以内に応答した場合と30分後に応答した場合とでは、コンタクト成功率に最大100倍の差が生じることが示されている。ナーチャリングは「長期育成」の文脈で語られることが多いが、ホットリードへの即時応答と中長期フォローは車の両輪であり、どちらが欠けても成果は出にくい。",
      "Meeton ai（AI SDR Platform）は、Webサイト訪問者との会話・資料提案・商談予約・追客メールを4つのモジュール（Meeton Calendar / Chat / Library / Email）で自律的に処理する。従来、人手に依存していた初動フォローと継続ナーチャリングをAIが24時間対応することで、Speed to Leadの課題とリード放置の両方をカバーできる設計になっている。用語としてのリードナーチャリングを理解した上で、実装をどう自動化するかを検討する際の参考にしてほしい。"
    ],
    "faq": [
      {
        "q": "リードナーチャリングとリードジェネレーションの違いは？",
        "a": "リードジェネレーションは「見込み顧客を新規に獲得する活動」であり、広告・SEO・展示会などが該当する。リードナーチャリングはその後工程で、「獲得済みのリードを温め、購買意欲を引き上げる活動」を指す。両者は独立した施策ではなく、デマンドジェネレーション全体の中で連続したプロセスとして設計するのが一般的である。"
      },
      {
        "q": "ナーチャリングに最適なコンテンツの種類は？",
        "a": "購買ステージによって異なる。認知・課題把握フェーズにはブログ記事・動画・ウェビナーが有効で、比較・検討フェーズにはホワイトペーパー・事例資料・ROI計算ツールが機能しやすい。意思決定フェーズでは無料トライアル・デモ案内・導入事例インタビューが商談化を後押しする。チャネルとしてはメールが依然として主力で、ナーチャリングメールの平均CTRは汎用メールの約2.7倍という報告がある（Sender.net調査）。"
      },
      {
        "q": "MAツールなしでリードナーチャリングを始めることはできるか？",
        "a": "小規模であれば可能である。CRMでリードをステージ別に管理し、スプレッドシートでコンテンツカレンダーを組み、メール配信ツール（MailchimpやHubSpotの無料プランなど）でシーケンスを設定するだけでも基本的なナーチャリングは実現できる。ただし、リード数が増えるにつれてスコアリングや行動トリガー配信が手動では追いつかなくなるため、一定規模を超えたらMAツールまたはAIエージェントの導入を検討するとよい。"
      }
    ],
    "related": [
      "sales-engagement",
      "ai-sdr",
      "shodanka-ritsu"
    ],
    "metaTitle": "リードナーチャリングとは？意味・手法・成功のコツをわかりやすく解説｜Meeton ai 用語集",
    "metaDescription": "リードナーチャリングとは、獲得した見込み顧客に継続的な情報提供を行い購買意欲を高める育成活動。B2Bバイヤーの57〜70%は自己調査で意思決定しており、放置すれば競合に流れる。手法・FAQ・ツール選定のポイントを解説。"
  },
  "mql-sql": {
    "slug": "mql-sql",
    "term": "MQL / SQL",
    "cluster": "ai-sdr",
    "shortDef": "MQL（Marketing Qualified Lead）とは、マーケティング部門が「営業に引き渡す価値がある」と判断した見込み顧客のことで、SQL（Sales Qualified Lead）はそこからさらに営業部門が「商談化できる」と判断したリードを指す。両者は同一リードが購買プロセスを進む中で呼称が変わる「ステージ」であり、マーケと営業の連携基準を言語化するための共通定義として機能する。",
    "body": [
      "MQL（Marketing Qualified Lead）は、マーケティング部門が設定したスコアリング基準を満たした見込み顧客を指す。典型的な判定材料は、特定ページの閲覧・資料ダウンロード・ウェビナー参加・メール開封率などの行動データに加え、業種・企業規模・役職といった属性情報の組み合わせだ。MAL（Marketing Accepted Lead）から始まるリードがナーチャリングを経てMQLに昇格するという段階的ファネルを採用する企業も多い。重要なのはMQLの定義は各社が自社の商材・商談サイクル・組織構造に合わせて設計するものであり、業界共通の固定値はない点だ。",
      "SQL（Sales Qualified Lead）は、MQLを受け取った営業部門（またはインサイドセールス）がBANT（Budget／Authority／Need／Timeline）などの基準で精査し「アポイント・商談に進める」と判断したリードを指す。日本のBtoB組織ではMAL→MQL→SAL（Sales Accepted Lead）→SQLという4ステージを設ける場合と、SALを省略してMQL→SQLの2段階で管理する場合がある。SALを設けると「マーケの送り出し基準」と「インサイドセールスの受け取り基準」を分離できるため、質の低いリードの押し付け合いを防ぎ部門間の合意形成が容易になる。",
      "MQL/SQLの区分が組織にもたらす最大の価値は、マーケと営業が同じ言語で話せる「引き渡し基準の明確化」にある。この定義が曖昧なまま運用されると、営業は「マーケが送ってくるリードの質が低い」と不満を持ち、マーケは「営業がちゃんとフォローしない」と感じるという、典型的なサイロ化が起きる。また、Forresterなどの調査によればB2B購買者の57〜70%は営業担当者に接触する前にすでに情報収集を終えているとされ、その段階でのリードシグナルをMQL基準として取り込むことが現代のインバウンドマーケティングでは不可欠になっている。",
      "MQLからSQLへの転換率（MQL-to-SQL Conversion Rate）は業種やチャネルによって大きく異なるが、B2B SaaSの参考値として12〜21%程度が広く引用されている（First Page Sage, 2026）。また、リードへの初回接触スピードも転換率に直結する。MIT Lead Response Management Studyなど複数の研究によれば、問い合わせから5分以内に対応した場合と30分以降に対応した場合では、コンタクト成功率に大きな差が生じるとされている。Meeton aiのAI SDRモジュール（Meeton Chat / Calendar）はこの「Speed to Lead」の課題に対応するものの一つとして設計されており、Webサイト上のMQLを検知した瞬間に会話・資料提案・商談予約を自動化する用途で活用される。"
    ],
    "faq": [
      {
        "q": "MQLとSQLは誰が決めるのか？",
        "a": "MQLはマーケティング部門が設定したスコアリングや行動基準に基づいて判定し、SQLは営業部門（またはインサイドセールス）がBANTや商談可否の観点で判断する。重要なのは両部門が合意した定義をドキュメント化し、定期的に見直すことで、組織間の齟齬を防げる。"
      },
      {
        "q": "MQL・SQLの基準はどう設定すればよいか？",
        "a": "まず自社の過去の受注データを分析し、受注に至ったリードに共通する行動パターンや属性を抽出することが出発点となる。スコアリングモデルではページ閲覧・フォーム送信・資料DLなどにポイントを付与し、閾値を超えたリードをMQLと定義するのが一般的だ。初期値は仮設定で構わず、実績データをもとに四半期ごとに調整するアジャイルな運用が推奨される。"
      },
      {
        "q": "MQLをSQLに引き上げるためにはどうすればよいか？",
        "a": "リードナーチャリング（メール・コンテンツによる継続的な情報提供）と、適切なタイミングでのインサイドセールスによるアウトリーチの組み合わせが有効だ。特に問い合わせや行動シグナルが発生した直後の初回接触スピードがコンタクト率・商談化率に影響するとされており、リードの「温度感が高いうちに」アプローチする体制を整えることが転換率改善の鍵となる。"
      }
    ],
    "related": [
      "ai-sdr",
      "shodanka-ritsu",
      "inbound-sales"
    ],
    "metaTitle": "MQL / SQLとは？定義・違い・設定方法をわかりやすく解説｜Meeton ai 用語集",
    "metaDescription": "MQL（Marketing Qualified Lead）はマーケ部門が「営業に渡す価値あり」と判断したリード、SQL（Sales Qualified Lead）は営業が「商談化できる」と判断したリードを指す。両者の違い・判定基準・転換率の目安をB2B実務の観点から解説。"
  },
  "inbound-sales": {
    "slug": "inbound-sales",
    "term": "インバウンド営業",
    "cluster": "ai-sdr",
    "shortDef": "インバウンド営業とは、見込み客が自らコンテンツや広告を通じて企業に接触・問い合わせてくる流れを設計し、その関心を商談・受注につなげる営業手法のことを指す。テレアポや飛び込みなど企業側から一方的にアプローチするアウトバウンド営業と対をなす概念であり、デジタル化による顧客の自己学習行動の高まりを背景に日本のBtoB市場でも普及が進んでいる。",
    "body": [
      "インバウンド営業とアウトバウンド営業の最大の違いは「誰が最初に動くか」にある。アウトバウンド営業は担当者がターゲットリストに電話・メールを送る能動的アプローチだが、インバウンド営業は見込み客の側が検索・資料ダウンロード・ウェビナー参加などを通じて企業に接触する。BtoB購買において、購買担当者が営業担当者に最初に連絡を取るまでに購買プロセスの約57〜70%を自己完結させているという調査（CEB/Gartner の研究が57%、Forrester の調査が70%と報告）が示すように、顧客はすでに相当量の情報収集を終えた段階で営業と話す。インバウンド営業はこの「接触前の自己学習フェーズ」に良質なコンテンツで存在感を示しておくことで、初回接触時点での温度感を高めることを目的とする。",
      "インバウンド営業とアウトバウンド営業の違いを軸ごとに整理すると理解しやすい。【起点】アウトバウンドは営業側、インバウンドは見込み客側が最初に動く。【主なチャネル】アウトバウンドはテレアポ・飛び込み・コールドメール、インバウンドはSEO記事・ホワイトペーパー・ウェビナー・Web問い合わせ・チャット。【リードの温度】アウトバウンドは相手の関心が不明な状態から始まるため低め、インバウンドは自発的に接触してくるぶん高くなりやすい。【商談化率の傾向】一般に自発的なインバウンドリードのほうが商談化率は高くなりやすい（BtoBのWeb問い合わせ経由の商談化率は業界平均で約20%が一つの目安とされる）。【成果が出るまでの時間】アウトバウンドは即日でも当たれるが、インバウンドはコンテンツ資産が育つまで数か月単位の助走期間を要する。【コスト構造】アウトバウンドは人件費・架電コストが件数に比例、インバウンドは初期のコンテンツ投資が資産化し中長期の効率が高い。【向く場面】特定企業をピンポイントで狙うならアウトバウンド、幅広い潜在層から継続的にリードを集めるならインバウンドが向く。実務では両者を組み合わせるハイブリッドが主流だ。",
      "アウトバウンド営業との比較で見るインバウンド営業のメリットとデメリットも整理しておきたい。メリットとしては、(1) 自発的に関心を示したリードは成約率が高くなりやすい、(2) コンテンツ資産は長期的に流入を生み続けるため中長期のコスト効率が高い、(3) 顧客に「売り込まれた」という印象を与えにくい点が挙げられる。一方で、デメリットとして、(1) 検索流入やホワイトペーパーDLが安定するまで数か月単位の投資期間が必要、(2) 訴求したい特定企業・特定ターゲットに絞り込みにくい、(3) 受け身の設計が過ぎると刈り取り機会を逃すリスクがある点も念頭に置く必要がある。実務上は、インバウンドで育てたリードに対してアウトバウンド的なフォローを組み合わせるハイブリッド戦略をとる企業が多い。",
      "インバウンド営業の主な施策は、大きく「流入獲得」と「リード育成・転換」の二段階に分けられる。流入獲得では、SEOを意識したオウンドメディア記事・ホワイトペーパー・ウェビナー・SNS発信・プレスリリースが代表的だ。リード育成・転換の段階では、メールシーケンスやMAツールを用いたリードスコアリング、そして問い合わせ後の迅速なフォローアップが鍵を握る。Harvard Business Review（2011年）の研究では、Webからの問い合わせに1時間以内に応答した企業は、1時間後に応答した企業に比べてリードを商談化できる確率が約7倍高いと報告されている（いわゆる「Speed to Lead」）。流入施策の充実と同時に、問い合わせ後の応答速度と応答品質を整えることが成果に直結する。",
      "インバウンド営業で見落とされがちなのが「初動対応（Speed to Lead）の速さが商談化率を決める」という点だ。自ら問い合わせてきたインバウンドリードは、接触したその瞬間が最も購買意欲の高い『ゴールデンウィンドウ』にある。しかし多くのBtoB企業では担当者の手動対応に依存し、返信までに数時間〜数十時間かかることも珍しくなく、その間にリードの温度感は冷め、競合に先を越されてしまう。BtoBのWeb問い合わせ経由の商談化率は業界平均で約20%が一つの目安とされるが、初動対応を秒単位まで速めるだけでこの数字は大きく変わる。実際、Webサイト上のAIが初動5秒で応答し、24時間365日リードを取りこぼさない仕組みを導入したEdulinXでは、商談化率60%以上を達成している。初動対応の詳細は関連用語『Speed to Lead（初動レスポンス）』で扱っており、会話から商談予約までを自動化する Meeton Calendar と組み合わせることで、インバウンドリードの熱量が高いうちに商談化まで到達できる。",
      "インバウンドリードを商談化する実務ステップは、大きく5段階で設計するとよい。第一に『即時応答』——問い合わせ・チャット・資料請求が発生した瞬間に自動で一次応答する（JSタグ1行・約5分で設置できるチャットを使えば、営業時間外の流入も取りこぼさない）。第二に『ヒアリングと選別』——課題・予算・検討度合いをBANTなどの観点で会話しながら確認し、確度の高いリードを見極める。第三に『関連資料の提案』——相手の関心に合った事例やサービス資料を提示し、比較検討を後押しする。第四に『商談枠の即時提示』——熱量が高いうちに、その場でカレンダーから空き枠を提示して予約まで完了させる。第五に『未予約リードへの追客』——その場で予約に至らなかったリードにも、行動シグナルに応じて1対1のフォローを継続する。この5ステップを人手の稼働に依存せず24時間365日回し続けられるかどうかが、インバウンド営業の成果を分ける。",
      "Webサイト上でのインバウンド動線を強化する文脈では、チャットボットや会話型AIの活用が近年注目されている。問い合わせフォームだけでなく、訪問者の関心に応じてリアルタイムで質問に答え、資料を提案し、商談予約まで完結させる仕組みを設けることで、「夜間・休日の流入を取りこぼさない」「営業担当がいない時間帯でも初期ヒアリングを完了させる」といった効果が期待できる。Meeton ai（DynaMeet）は、このインバウンド動線の自動化を目的として設計されたAI SDRプラットフォームであり、会話・資料提案・日程調整・追客の4モジュール（Meeton Calendar / Chat / Library / Email）をWebサイトに組み込んで活用できる。用語の解説という観点に戻ると、インバウンド営業は単なる「待ちの営業」ではなく、コンテンツ投資・導線設計・レスポンス速度・育成ロジックの総合力が問われる体系的な営業モデルだと理解することが重要だ。"
    ],
    "faq": [
      {
        "q": "インバウンド営業とは何ですか？",
        "a": "インバウンド営業とは、見込み客が検索・資料ダウンロード・ウェビナー参加などを通じて自ら企業に接触してくる流れを設計し、その関心を商談・受注へ転換する営業手法です。企業側から電話や訪問でアプローチするアウトバウンド営業と対をなす概念で、良質なコンテンツで『接触前の自己学習フェーズ』に存在感を示し、問い合わせ後は迅速な初動対応で商談化につなげるのが基本です。"
      },
      {
        "q": "インバウンド営業とアウトバウンド営業の違いは何ですか？",
        "a": "最大の違いは『誰が最初に動くか』です。アウトバウンド営業は営業担当者がターゲットリストへ電話・メールを送る能動的アプローチで、特定企業をピンポイントで狙え即日でも着手できる一方、リードの温度感は不明な状態から始まります。インバウンド営業は見込み客が自発的に接触してくるためリードの温度感が高く商談化率が高くなりやすい反面、コンテンツ資産が育つまで数か月の助走期間を要します。実務では両者を組み合わせるハイブリッド運用が主流です。"
      },
      {
        "q": "インバウンド営業の商談化率を上げるにはどうすればよいですか？",
        "a": "鍵は『初動対応（Speed to Lead）の速さ』です。自ら問い合わせてきたインバウンドリードは接触した瞬間が最も購買意欲が高く、初動が遅れるほど温度感が冷めます。BtoBのWeb問い合わせ経由の商談化率は業界平均で約20%が目安とされますが、問い合わせ直後に即応答し、会話・資料提案・商談予約までその場で完結させることで大きく引き上げられます。実際、初動5秒で応答し24時間365日リードを取りこぼさないAIを導入したEdulinXは商談化率60%以上を達成しています。"
      },
      {
        "q": "インバウンド営業とインバウンドマーケティングの違いは何ですか？",
        "a": "インバウンドマーケティングは、SEOやコンテンツ・SNSなどを通じて見込み客を自社に引き寄せる「流入獲得」の活動全般を指す。インバウンド営業（インバウンドセールス）は、その流入によって生まれたリードを商談・受注に転換する「営業プロセス」を指す。マーケティング部門がリードを創出し、営業部門がクロージングを担うという役割分担が一般的だが、中小企業では一体で運用するケースも多い。"
      },
      {
        "q": "インバウンド営業を始めるには何から手をつければよいですか？",
        "a": "まず「誰のどんな課題を解決するか」というペルソナと課題の整理を行い、そこからSEO記事やホワイトペーパーなどコンテンツの優先順位を決めるのが定石だ。同時に、流入後のCTA（資料DL・問い合わせフォーム・チャット）と、問い合わせ後の応答フロー（自動返信・担当者アサイン・フォローメール）を整備しておくことが重要で、流入だけ増やしても応答速度や品質が低ければ商談化率は上がらない。"
      }
    ],
    "related": [
      "ai-sdr",
      "shodanka-ritsu",
      "speed-to-lead",
      "mql-sql"
    ],
    "metaTitle": "インバウンド営業とは？意味・アウトバウンドとの違い・商談化のコツ｜Meeton ai 用語集",
    "metaDescription": "インバウンド営業とは、見込み客が自ら検索・資料請求・問い合わせしてくる流れを設計し、商談・受注につなげる営業手法です。アウトバウンドとの違いや比較、Speed to Lead（初動対応）で商談化率を高める実務ステップまで、BtoB担当者向けにわかりやすく解説します。"
  },
  "sales-engagement": {
    "slug": "sales-engagement",
    "term": "セールスエンゲージメント",
    "cluster": "email",
    "shortDef": "セールスエンゲージメントとは、営業担当者が見込み顧客・既存顧客とメール・電話・SNS・チャットなど複数チャネルで行うコミュニケーション全体を体系的に管理・最適化し、信頼関係の構築と受注確度の向上を同時に実現する営業戦略・プロセスの総称である。近年はこれを自動化・分析するソフトウェア（セールスエンゲージメントプラットフォーム）を指す場合も多い。",
    "body": [
      "セールスエンゲージメントが注目される最大の背景は、B2B購買行動の変化にある。Forrester の調査によれば、B2B バイヤーの約70%は営業担当者に初めて接触する時点ですでに購買プロセスの大半を終えている。つまり顧客は、営業が連絡を取る前にオウンドメディア・口コミ・比較サイトで候補を絞り込んでいる。このような環境では「待ちの営業」では機会を失い、適切なタイミングで適切なチャネルから価値のある情報を届ける能動的なエンゲージメントが差別化の鍵となる。",
      "セールスエンゲージメントの実務的な核心は「シーケンス（連絡手順の自動化）」と「インタラクション計測」にある。見込み顧客ごとにメール・電話・SNS のアプローチ順序とタイミングをあらかじめ設計し、反応（開封・クリック・返信）をリアルタイムで追跡することで、次のアクションを最適化する。また Harvard Business Review と MIT の共同研究では、問い合わせから5分以内に初回接触した場合の商談化率は、30分後に接触した場合と比べて最大21倍になることが示されており、Speed to Lead（初動の速さ）がエンゲージメント品質を大きく左右することが明らかになっている。",
      "CRM・SFA との違いも押さえておきたい。CRM は顧客情報の蓄積と管理が主目的であり、SFA は営業プロセスの可視化・進捗管理に特化する。対してセールスエンゲージメントは「実際のコミュニケーション実行と効果測定」に焦点を当てており、CRM・SFA と連携して補完的に機能するのが一般的だ。セールスイネーブルメントとも混同されやすいが、イネーブルメントが「営業担当者の育成・組織力強化（社内向け）」であるのに対し、セールスエンゲージメントは「顧客との接点そのものの質・量を高める（社外向け）」活動である。",
      "AI の進化により、セールスエンゲージメントは従来の「メール一括配信 + CRM 記録」から、会話・資料提案・予約・フォローアップを自律的に実行する AI エージェント型へと進化しつつある。Meeton ai はWebサイト上でこの役割を担う AI SDR プラットフォームであり、Meeton Chat（会話）・Calendar（商談予約）・Library（資料提案）・Email（追客）の4モジュールが連携して、24時間・無人でセールスエンゲージメントを実行する設計となっている。"
    ],
    "faq": [
      {
        "q": "セールスエンゲージメントとセールスイネーブルメントの違いは？",
        "a": "セールスエンゲージメントは「顧客との接点の質・量を高める社外向け活動」、セールスイネーブルメントは「営業担当者のスキル・知識・ツールを整備する社内向け活動」です。前者はコミュニケーション実行、後者は組織づくりが中心であり、両者は補完関係にあります。"
      },
      {
        "q": "セールスエンゲージメントプラットフォームとCRMは何が違うのか？",
        "a": "CRMは顧客情報の記録・管理が主目的ですが、セールスエンゲージメントプラットフォームはメール・電話・SNSなどの実際のコミュニケーション実行と反応計測（開封率・返信率など）に特化しています。多くの場合、両者は連携させて使います。"
      },
      {
        "q": "セールスエンゲージメントを導入すると何が改善されるか？",
        "a": "主な改善点は3つです。①シーケンス自動化によるフォローアップ漏れの防止、②反応データに基づくメッセージ・タイミングの最適化、③問い合わせへの初動速度（Speed to Lead）の向上です。これらが複合することで、商談化率や成約率の改善につながりやすくなります。"
      }
    ],
    "related": [
      "lead-nurturing",
      "ai-sdr",
      "shodanka-ritsu"
    ],
    "metaTitle": "セールスエンゲージメントとは？定義・CRM/SFAとの違い・活用法｜Meeton ai 用語集",
    "metaDescription": "セールスエンゲージメントとは、メール・電話・SNSなど複数チャネルで顧客とのコミュニケーションを体系的に管理・最適化する営業戦略の総称。CRM・SFA・セールスイネーブルメントとの違いや、B2B営業における活用法をわかりやすく解説します。"
  },
  "web-sekkyaku": {
    "slug": "web-sekkyaku",
    "term": "Web接客",
    "cluster": "chat",
    "shortDef": "Web接客とは、Webサイトを訪れたユーザーに対してチャットボット・ポップアップ・ライブチャットなどを通じてリアルタイムまたは自律的に対話・案内を行い、コンバージョンや顧客満足度を高める施策の総称である。実店舗の接客をオンラインで再現するものと捉えると分かりやすく、近年はAIの台頭によりB2B領域でも急速に普及している。",
    "body": [
      "Web接客とは、Webサイト上でユーザーの行動に応じて能動的に働きかけ、情報提供・課題のヒアリング・次のアクションへの誘導を行う施策の総称である。主な手段はポップアップ型（閲覧行動に連動して訴求バナーを表示）、チャット型（ボットまたは有人オペレーターが質問に応答）、複合型（両者を組み合わせたハイブリッド）の3種類に分類される。BtoCでの活用が先行したが、現在はBtoBサイトでも導入が進んでいる。",
      "BtoBにおいてWeb接客が重要視される背景には、購買行動の変化がある。Gartnerが2025年8〜9月に646名のB2Bバイヤーを対象に実施した調査（2026年3月公表）によると、67%のB2Bバイヤーが営業担当者を介さない購買体験を好むと回答している。つまり多くの見込み客は、営業に連絡する前にWebサイト上で情報収集・比較検討をほぼ完了させる。この段階でリアルタイムに質問へ答え、適切なコンテンツや商談枠を提示できるかどうかが、商談化率を左右するポイントとなる。",
      "Web接客の効果として期待できるのは、主にCVR（コンバージョン率）の向上、離脱防止、および営業工数の削減である。チャットボットが24時間対応することで、営業時間外の問い合わせも取りこぼさず受け付けられる。一方で、導入後の運用設計（シナリオ改善・A/Bテスト・PDCA）を怠ると効果が頭打ちになりやすい点には注意が必要である。ツール選定時には「効果測定機能が備わっているか」「CRM・MAと連携できるか」を確認することが推奨される。",
      "AIの進化により、Web接客は「シナリオ型チャットボット」から「自律型AIエージェント」へとシフトしつつある。従来のシナリオ型は事前に想定した質問の範囲でしか対応できなかったが、生成AIを活用した自律型は文脈を理解して柔軟に応答し、資料提案・商談予約・フォローアップまでを一貫して自動化することが可能になってきた。Meeton aiはこうした自律型Web接客をB2Bサイト向けに実現するAI SDRプラットフォームであり、会話・資料提案・予約・追客の4モジュール（Meeton Calendar / Chat / Library / Email）で構成されている。"
    ],
    "faq": [
      {
        "q": "Web接客ツールとチャットボットは何が違うのか？",
        "a": "チャットボットはWeb接客ツールの一種である。Web接客ツールはポップアップ・ライブチャット・レコメンドなどを含む広い概念であり、チャットボットはその中で会話形式の自動応答に特化した機能を指す。近年はチャットボットがWeb接客の中核を担うケースが多いが、ポップアップのみ利用する形態もWeb接客に含まれる。"
      },
      {
        "q": "BtoBでWeb接客は本当に効果があるのか？",
        "a": "Gartner（2026年3月公表）によるとB2Bバイヤーの67%が営業担当者を介さない体験を好むとされており、Webサイト上での接点がBtoBでも決定的に重要になっている。実際に製造業や人材・IT系SaaS企業での導入事例では、問い合わせ数増加や営業工数削減の効果が報告されている。ただし効果の大きさはサイトのトラフィック量・シナリオ設計の質・継続的な改善によって大きく異なる。"
      },
      {
        "q": "Web接客ツールを選ぶ際の主な判断軸は何か？",
        "a": "主な判断軸は(1)対応形式（ポップアップ・チャット・複合型）、(2)AI・シナリオの柔軟性、(3)CRM・MAとの連携可否、(4)効果測定・A/Bテスト機能の有無、(5)運用コスト（初期費用・月額・社内工数）の5点である。BtoBサイトでは有人対応の有無や商談予約機能との連携も重要な選定ポイントとなる。"
      }
    ],
    "related": [
      "ai-sdr",
      "shodanka-ritsu",
      "speed-to-lead"
    ],
    "metaTitle": "Web接客とは？種類・BtoBでの効果・AI活用の最前線｜Meeton ai 用語集",
    "metaDescription": "Web接客とは、チャットボット・ポップアップなどでWebサイト訪問者にリアルタイムに働きかけ、CVRや商談化率を高める施策の総称。BtoBでの活用背景、ツールの種類と選び方、AI自律型への最新トレンドをわかりやすく解説します。"
  },
  "document-open-rate": {
    "slug": "document-open-rate",
    "term": "資料開封率",
    "cluster": "library",
    "shortDef": "資料開封率とは、営業担当者や施策が送付した提案書・サービス資料などのドキュメントを、受信者が実際に開いた割合を示す指標のことです。メール開封率と区別され、\"コンテンツに触れたか\"を可視化することで、見込み顧客の購買関心度とフォローアップ適切なタイミングを判断する根拠として活用されます。",
    "body": [
      "資料開封率は、「送付した資料が閲覧されたかどうか」を数値で把握する指標です。計算式は「資料を開封した件数 ÷ 送付した件数 × 100」で表され、DocSend・HubSpot Sales・Highspot などのセールスイネーブルメントツールが採用するドキュメントトラッキング機能によって計測されます。メール開封率がメールを開いたかどうかを測るのに対し、資料開封率は「添付またはリンクされた資料そのものが閲覧されたか」を測る点が異なります。閲覧時間・閲覧ページ・閲覧デバイスなどの付帯データも取得できるため、単純な開封の有無より深いエンゲージメント分析が可能です。",
      "資料開封率が重視される背景には、B2B購買行動の変化があります。CEB（現Gartner）の調査では、B2Bバイヤーが営業担当者と初めてコンタクトを取る時点で、購買プロセスの約57%が自己完結していると報告されており、Forresterの調査（2019年）ではこの割合が70%に達するという見方も示されています。つまり、見込み顧客は営業との対話が始まる前に相当量の情報収集と比較を終えています。この状況において、送付した資料が「いつ・何ページまで・どれほどの時間閲覧されたか」を把握することは、見込み顧客の関心フェーズを推定し、最適な接触タイミングを見極める手がかりになります。",
      "資料開封率は、ホットリード判定とフォローアップ速度の両面で活用されます。資料送付後に閲覧シグナルを検知した直後にアプローチすることは、Harvard Business Reviewが言及したSpeed to Leadの概念と重なります。同研究では、リードが発生してから5分以内に接触した場合、30分後に接触した場合と比べてコネクト確率が100倍・リード資格化の確率が21倍になると報告されています。資料開封率を起点に「資料を開封した直後に連絡する」という仕組みを設計することで、この効果を営業現場に実装できます。MAツールやCRMと連携すれば、スコアリングの一要素として自動化することも可能です。",
      "Meeton ai の Meeton Library モジュールは、Webサイト上に配置したAIエージェントが来訪者の関心に合わせて資料を提案し、その閲覧シグナルをもとに後続の会話・予約・追客フローへ自動で引き渡す設計になっています。「資料を送って終わり」にせず、開封率などのエンゲージメントデータをパイプライン管理に組み込むことで、タイミングを逃さない商談化を目指しています。"
    ],
    "faq": [
      {
        "q": "資料開封率とメール開封率は何が違いますか？",
        "a": "メール開封率はメール本文を開いたかどうかを測りますが、資料開封率はメールに添付またはリンクされた提案書・サービス資料などのドキュメントを実際に閲覧したかどうかを測る指標です。資料開封率は「コンテンツへの接触」をより直接的に示すため、購買関心の度合いをより正確に反映すると考えられています。"
      },
      {
        "q": "資料開封率の目安（平均値）はどのくらいですか？",
        "a": "資料開封率の業界横断的な標準ベンチマークは現時点では確立されていません。ただし参考値として、DocSendが3400万件超のコンテンツインタラクションを分析した報告によると、提案書の平均閲覧完了率や時間帯などのデータは得られています。メール開封率の国内BtoBの実態（IDEATECHの調査では11〜30%が最多）とは別の指標であるため、自社の過去送付実績を基準にした相対的な改善を目標にすることが実務的です。"
      },
      {
        "q": "資料開封率を上げるにはどうすればよいですか？",
        "a": "主なアプローチは3点です。(1) 送付タイミング：商談や問い合わせ直後など、関心が高いタイミングで送る。(2) 資料そのもの：冒頭ページで価値を明示し、ページ数を絞って離脱を減らす。(3) 通知設定：閲覧シグナルを即座に受け取れるトラッキングツールを使い、開封後すぐにフォローアップすることで、次の接点への転換率を高められます。"
      }
    ],
    "related": [
      "ai-sdr",
      "shodanka-ritsu",
      "speed-to-lead"
    ],
    "metaTitle": "資料開封率とは？定義・活用方法・メール開封率との違い｜Meeton ai 用語集",
    "metaDescription": "資料開封率とは、送付した提案書や営業資料が実際に閲覧された割合を示すB2B営業指標です。ホットリード判定やフォローアップタイミングの最適化に活用され、メール開封率とは区別して扱われます。定義・計算式・活用法を解説。"
  },
  "bant": {
    "slug": "bant",
    "term": "BANT",
    "cluster": "ai-sdr",
    "shortDef": "BANTとは、B2B営業においてリードの商談化可否を判断するためのヒアリングフレームワークで、Budget（予算）・Authority（決裁権）・Need（必要性）・Timeline（導入時期）の4要素の頭文字を組み合わせた言葉です。IBMが1950年代に体系化したとされ、インサイドセールスからフィールドセールスまで幅広く使われる基本資格要件として定着しています。",
    "body": [
      "BANTは「Budget（予算）」「Authority（決裁権）」「Need（必要性）」「Timeline（導入時期）」の4要素を指す。Budgetは自社製品・サービスに充てられる予算規模、Authorityは契約の最終決裁を持つ人物への到達度、Needは顧客が抱える課題と自社ソリューションの適合度、Timelineは導入・検討開始の目標時期を指す。4要素すべてが揃ったリードを「BANT条件を満たした有望案件」として優先的に商談化する運用が一般的だ。",
      "BANTはシンプルな反面、現代のB2B購買行動との乖離が指摘されることもある。Forrester・6sense などの調査では、B2Bバイヤーが営業担当者に初めて接触する時点で、購買検討の57〜70%が既に完了していることが報告されている。つまりBANTのヒアリング機会が訪れた段階では、顧客の意思決定の大部分が自己完結していることも多い。そのため、BANTを「会話で一気に聞き出す質問リスト」として使うのではなく、複数タッチポイントにわたって段階的に情報収集するためのチェックリストとして活用する企業が増えている。",
      "BANT情報をいかに早く・正確に把握するかも重要な競争要素だ。Harvard Business Reviewが引用している調査では、問い合わせから1時間以内に応答した企業は、1時間以上待った企業より意思決定者との有意義な会話を得られる可能性が7倍高いとされる（Lead Response Management Study）。応答速度がBANT確認の機会そのものを左右するという点で、「Speed to Lead」はBANT活用の前提条件といえる。",
      "Meeton ai（AI SDR Platform）では、Webサイトに配置したチャットボット（Meeton Chat）が訪問者との会話を通じてBudget・Need・Timelineに相当する情報をリアルタイムに収集し、Meeton Calendarで有望リードの商談枠を即時案内、Meeton Emailで後続フォローを自動化する設計になっている。BANTの各要素をツールが段階的に補完することで、営業担当者が本当に商談化すべきリードに集中できる環境を目指している。"
    ],
    "faq": [
      {
        "q": "BANTとCHAMPやMEDDICはどう違うのか？",
        "a": "BANTが予算・決裁・必要性・時期を軸とするのに対し、CHAMPはChallenges（課題）を最優先にした顧客視点の変形版、MEDDICは定量的な経済的効果（Metrics）や決裁プロセスの特定（Decision Process）を加えたエンタープライズ向けの拡張版です。自社商材の複雑度や販売サイクルの長さに応じて使い分けるのが一般的です。"
      },
      {
        "q": "BANTは電話・メールのどちらで確認するのが効果的か？",
        "a": "決まった正解はなく、商材単価や関係性の深さによって異なります。初回の電話やウェビナー後のフォローメールで概況を掴み、商談前の事前アンケートや資料ダウンロード時のフォームでBudget・Timelineを補足するハイブリッド運用が実務では多く採られています。"
      },
      {
        "q": "BANTが4要素すべて揃わなくても商談化してよいか？",
        "a": "揃っていない要素があっても商談化する判断は十分あり得ます。特にNeedが明確でTimelineが短い場合、予算や決裁ルートは商談を通じて作り込むことが可能です。BANTは「全項目が揃わないと動かない」ルールではなく、優先度と次アクションを決めるための判断材料として使うのが現実的です。"
      }
    ],
    "related": [
      "ai-sdr",
      "shodanka-ritsu",
      "mql-sql"
    ],
    "metaTitle": "BANTとは？意味・使い方・現代営業での限界と活用法｜Meeton ai 用語集",
    "metaDescription": "BANTとはBudget・Authority・Need・Timelineの4要素でリードを評価するB2B営業の定番フレームワーク。IBMが体系化した手法の意味・使い方・現代B2Bでの限界と活用のポイントをわかりやすく解説します。"
  },
  "plg": {
    "slug": "plg",
    "term": "PLG（プロダクトレッドグロース）",
    "cluster": "ai-sdr",
    "shortDef": "PLG（プロダクトレッドグロース）とは、製品そのものをユーザー獲得・転換・拡大の主エンジンとするGo-to-Market戦略で、フリープランや無料トライアルで先に価値を体験させ、納得したユーザーが自発的に有料へ移行する仕組みを指す。従来の営業主導型（SLG）と対比され、SaaS・B2Bソフトウェア領域で急速に普及している。",
    "body": [
      "PLG（プロダクトレッドグロース）とは、「製品を使ってみること」自体を顧客獲得の起点にするGo-to-Market戦略だ。従来のSLG（セールスレッドグロース）では、営業担当者がデモや提案書で価値を伝えてから初めて試用に進むが、PLGでは順序が逆になる。まずフリープラン・無料トライアル・インタラクティブデモで製品を体験させ、その体験価値をもとにアップグレードを促す。意思決定者だけでなく現場ユーザーが自分で試せる点が、ITツールの購買行動の変化と合致している。Forrester の調査（2019年）や 6sense の調査（900人超のB2Bバイヤー対象）では、B2Bバイヤーの約70%が購買プロセスの大部分を自己リサーチで完了してから営業に接触する、と報告されており、PLGはこの「先に調べたい」心理と親和性が高い。",
      "PLGを実現するうえで重要な概念が PQL（Product Qualified Lead）だ。MQL（マーケティング経由のリード）やSQL（営業評価済みリード）と異なり、PQLは「製品の利用行動そのもの」でリードを評価する。たとえば、無料トライアル中に特定の機能を複数回使用したユーザー、チームメンバーを招待したユーザーなどが該当する。ProductLed の調査によると、PQLを活用している企業はそうでない企業と比べてフリー→有料の転換率が約3倍になる傾向があり、フリーミアムモデルでの訪問者転換率の中央値は約12%と報告されている（ProductLed Benchmarks）。ただし製品の複雑さやACV（年間契約単価）によって数値は大きく異なるため、自社プロダクトのコンテキストで検証することが不可欠だ。",
      "PLGはすべてのB2B製品に適しているわけではない。単価が比較的低く、エンドユーザー自身が導入判断できる製品（ACV 1万ドル未満が目安とされることが多い）で特に機能しやすい。一方、導入に複数ステークホルダーの合意が必要な高額製品や、専門的なオンボーディングが必須の製品はSLGの方が適合するケースがある。近年注目されているのが「PLS（プロダクトレッドセールス）」と呼ばれるハイブリッドモデルで、PLGで効率的に獲得・スクリーニングしたユーザーのうち、エンタープライズ化の見込みが高いアカウントに対してのみ営業リソースを集中投下する戦略だ。McKinsey の分析でも、ARR 1,000万ドル超のSaaS企業の多くがこのPLSへの移行を進めていると報告されている。",
      "日本のB2B市場においても、PLGへの関心は急速に高まっている。国内のSaaS企業を中心に、フリープランの提供や製品内オンボーディングの整備が進んでいる。一方で、日本の商習慣（稟議・複数承認者・ベンダー評価プロセス）がPLGの「まず触ってみる」という流れと必ずしも噛み合わない場面もあり、純粋PLGよりもPLSハイブリッドが実態に合うケースが多いとされる。Webサイト上でのセルフ体験と、ホットリードへの迅速な営業フォローを組み合わせる設計が、日本市場でのPLG実践において現実的なアプローチとなっている。なお、Meeton ai のようなAI SDR Platformは、Webサイト訪問者に自律的にアプローチし、PLGで獲得したPQLへの即時フォローを自動化するような文脈でも活用される。"
    ],
    "faq": [
      {
        "q": "PLGとSLGの違いは何ですか？",
        "a": "SLG（セールスレッドグロース）は営業担当者が価値を伝えてから製品を試用させる順序であるのに対し、PLGは先に製品を体験させてから有料転換を促す順序が逆のモデルです。PLGは顧客獲得コスト（CAC）を抑えやすく、SLGは高単価・複雑な製品に向いています。近年は両者を組み合わせた「PLS（プロダクトレッドセールス）」ハイブリッドが主流になりつつあります。"
      },
      {
        "q": "PQL（プロダクト・クオリファイド・リード）とは何ですか？",
        "a": "PQLとは、フリープランや無料トライアルを通じて製品の価値を実際に体験し、有料転換の可能性が高いと判断されたリードのことです。MQL（マーケティング行動）やSQL（営業評価）ではなく「製品の利用行動」を基準にスコアリングする点が特徴で、PLG戦略における中心的な指標となります。"
      },
      {
        "q": "日本のB2Bでも PLGは機能しますか？",
        "a": "単価が比較的低くエンドユーザーが自己判断で導入できる製品では機能しやすいですが、稟議や複数承認が必要な高額製品には純粋PLGは合いにくい側面があります。現実的には、フリートライアルで関心を引きPQLを特定したうえで営業が介入する「PLSハイブリッド」が日本市場での有効なアプローチとされています。"
      }
    ],
    "related": [
      "ai-sdr",
      "shodanka-ritsu",
      "mql-sql"
    ],
    "metaTitle": "PLG（プロダクトレッドグロース）とは？SLGとの違い・PQLの意味も解説｜Meeton ai 用語集",
    "metaDescription": "PLG（プロダクトレッドグロース）とは、製品体験そのものを顧客獲得・転換の主エンジンとするGo-to-Market戦略。フリープラン・無料トライアルでユーザーが先に価値を体験し、自発的に有料移行する仕組み。SLGとの違い・PQL・日本B2Bでの実践方法をわかりやすく解説。"
  }
} as Record<string, GlossaryTerm>;

// ─────────────────────────────────────────────────────────────────────
// English mirror (GLOSSARY_EN). Same slugs/cluster/related as GLOSSARY,
// faithful translation — no new claims/numbers; figures and brand names
// (Meeton ai, DynaMeet, etc.) kept exact. Rendered by GlossaryLP when
// lang="en" via /en/glossary/* + /en/glossary.
// ─────────────────────────────────────────────────────────────────────

export const GLOSSARY_EN: Record<string, GlossaryTerm> = {
  "ai-sdr": {
    slug: "ai-sdr",
    term: "AI SDR",
    cluster: "ai-sdr",
    shortDef:
      "AI SDR (AI Sales Development Representative) is an umbrella term for software in which an AI agent autonomously performs, 24/7, the work that human inside-sales reps (SDRs) used to do—\"initial inquiry handling, lead qualification, content recommendation, meeting setting, and follow-up.\" Unlike a mere scripted chatbot, its biggest characteristic is that it interprets conversational context and buying intent and chooses the right action at the right time.",
    body: [
      "An SDR (Sales Development Representative) is a role dedicated to the initial handling and qualification of prospects, and is generally widespread in Western B2B sales organizations. AI has become able to autonomously handle the repetitive tasks an SDR does daily—instant replies to inquiries, lead scoring, meeting booking via calendar integration, and follow-up email sending. This \"AI that functions as an SDR\" is collectively called an AI SDR.",
      "In B2B purchasing, \"contact timing\" is directly tied to the meeting-conversion rate. According to a joint study by InsideSales.com and the MIT Sloan School of Management (Lead Response Management Study), the contact success rate differs by up to 8x between replying to an inbound lead within 5 minutes versus more than 5 minutes. Meanwhile, Forrester research reports that 57–70% of B2B buyers have already completed their own research before they first contact a sales rep, so a mechanism that does not miss the moment a prospect searches and visits on their own has become a competitive advantage. The AI SDR is attracting attention as something that fills this gap.",
      "AI SDRs are broadly classified into \"outbound\" and \"inbound\" types. The outbound type auto-generates and sends email / LinkedIn outreach to a target list and continues the conversation based on replies. The inbound type detects in real time prospects who visit a website or form and handles conversation, content recommendation, and scheduling end to end. In both, the current mainstream is a hybrid model where \"AI handles a large volume of repetitive work and human reps focus on closing and complex negotiation.\"",
      "Meeton ai, developed by DynaMeet, is positioned as an inbound-focused AI SDR Platform. Four modules placed on the website (Meeton Calendar / Chat / Library / Email) work together to autonomously execute, end to end, conversation with visitors, recommendation of relevant content, automatic booking of meeting slots, and follow-up toward meeting conversion. Refer to it as one example of a product approach to the challenge of \"not missing meeting opportunities even when sales reps are unavailable.\"",
    ],
    faq: [
      {
        q: "What's the difference between an AI SDR and a chatbot?",
        a: "A traditional chatbot only replies along pre-defined scenarios, whereas an AI SDR combines a large language model (LLM) with buying-intent analysis to autonomously choose the best next action (content recommendation, scheduling, escalation) based on conversational context, the visitor's behavior history, and the content on hand—this is the fundamental difference.",
      },
      {
        q: "Will AI SDRs replace human SDRs?",
        a: "At present, a \"role split\" rather than \"complete replacement\" is the realistic view. The mainstream as of 2026 is a hybrid model where AI handles high-volume repetitive processing (initial handling, scoring, follow-up) and human reps handle complex negotiation, trust building, and closing.",
      },
      {
        q: "Does how you use an AI SDR change between inbound and outbound?",
        a: "Yes. An outbound AI SDR automates outreach and reply handling to a target list, aiming to execute new prospecting at scale. An inbound AI SDR specializes in immediately handling, qualifying, and guiding to booking the prospects who—already interested in your service—visit your website or inquiry form, so the purpose and design philosophy differ.",
      },
    ],
    related: ["shodanka-ritsu", "mql-sql", "inbound-sales"],
    metaTitle: "What is an AI SDR?｜Meeton ai",
    metaDescription:
      "An AI SDR (AI Sales Development Representative) is an AI agent that autonomously performs lead handling, content recommendation, meeting booking, and follow-up. We clearly explain its definition, how it works, and the benefits of adoption in B2B sales.",
  },
  "speed-to-lead": {
    slug: "speed-to-lead",
    term: "Speed to Lead",
    cluster: "calendar",
    shortDef:
      "Speed to Lead is the time it takes from the moment a prospect shows interest—via a form submission, inquiry, etc.—to when a sales rep makes first contact. This speed is a critical sales metric directly tied to the lead meeting-conversion rate.",
    body: [
      "Speed to Lead refers to the time from when an inbound lead arises to when the first sales contact is made. In B2B sales, a lead's \"heat\" cools rapidly over time. A joint study by InsideSales.com (now XANT) and the Kellogg School of Management (MIT) showed that contacting within 5 minutes of a lead's creation makes the probability of successful lead qualification 21x higher than contacting 30 minutes later. The same study also reports that a first contact within 5 minutes makes the probability of establishing a meaningful conversation 100x higher than contacting 30 minutes later.",
      "The industry-average initial response time remains long, and multiple surveys show the average response time of B2B companies is on the order of tens of hours. A Harvard Business Review study reports that companies responding within 1 hour of a form submission were 7x more likely to have a meaningful conversation with a key person than companies that took 2 hours or more. Meanwhile, after 24 hours, the probability of qualification reportedly drops to less than one-sixtieth. According to HubSpot's 2024 State of Marketing Report, 82% of consumers expect an \"immediate response\" to an inquiry, and that benchmark is shifting from minutes to seconds.",
      "Behind why Speed to Lead is especially emphasized is the change in modern buying behavior. A CEB (now Gartner) study finds that B2B buyers have already completed about 57% of the buying process by the time they first contact a sales rep. Forrester Research also reports that 68% of B2B buyers prefer to gather information themselves on the web over interacting directly with a sales rep. In other words, the very moment a buyer voluntarily makes contact is the \"golden window\" of highest buying intent, and building a system that does not miss that moment becomes the source of a competitive edge.",
      "Effective means to shorten Speed to Lead include automatic email / SMS sending right after a form submission, immediate conversation start via chatbot, real-time routing to a rep by AI, and a mechanism that guides the prospect straight into a meeting booking during the conversation. Meeton ai, as an AI SDR Platform that autonomously handles conversation, content recommendation, booking, and follow-up the moment a lead arises on the website, can be used in the context of automating the shortening of Speed to Lead.",
    ],
    faq: [
      {
        q: "What is the target value (benchmark) for Speed to Lead in minutes?",
        a: "Based on the joint study by InsideSales.com and the Kellogg School of Management, \"within 5 minutes\" is widely used as a benchmark in the industry. A growing number of leading companies aim for within 60 seconds using chatbots and AI, but it is important to set a realistic target that fits your own industry and customer characteristics.",
      },
      {
        q: "How does Speed to Lead relate to SEO and marketing?",
        a: "The faster acquired leads are converted into meetings, the higher the ROI of ad spend and content investment. If the initial response to a hard-won lead is delayed, competitors may get ahead or buying intent may cool, so marketing results are eroded at the sales stage. Speed to Lead also functions as an alignment metric between marketing and sales.",
      },
      {
        q: "Is it hard for Japanese B2B companies to shorten Speed to Lead?",
        a: "In Japan, the culture of inserting a thank-you page after an inquiry and the prevalence of flows where reps manually assign leads tend to delay the initial response. However, by starting with measures that can be introduced without greatly changing cultural practices—such as auto-replies after a form submission or instant chatbot activation—you can shorten it step by step.",
      },
    ],
    related: ["inside-sales", "ai-sdr", "shodanka-ritsu"],
    metaTitle: "What is Speed to Lead?｜Meeton ai",
    metaDescription:
      "Speed to Lead is the time from a lead's creation to the first sales contact. Studies show responding within 5 minutes makes the qualification rate 21x higher, making it a critical metric that determines B2B sales success.",
  },
  "shodanka-ritsu": {
    slug: "shodanka-ritsu",
    term: "Meeting-conversion rate",
    cluster: "ai-sdr",
    shortDef:
      "Meeting-conversion rate is a sales KPI indicating the proportion of leads (prospects) acquired in a given period that actually advanced to a meeting. It is calculated as \"meeting-conversion rate (%) = number of converted meetings ÷ total leads × 100\" and is widely used as a basic metric for measuring pipeline efficiency from marketing to sales.",
    body: [
      "The meeting-conversion rate visualizes not the \"quantity\" of lead acquisition but its \"quality\" and \"conversion efficiency.\" For example, if 20 of 100 monthly leads advance to a meeting, the meeting-conversion rate is 20%. In typical B2B companies it is often cited as around 10–15% for outbound (cold calls / emails) and around 35–40% for inbound (web inquiries / content downloads), but because it varies greatly by industry, deal price, and channel mix, it is important to use your own past results as a baseline.",
      "One of the biggest factors affecting the meeting-conversion rate is \"contact speed.\" According to a Harvard Business Review study, there is a large difference in connect (conversation-established) probability between calling back within 5 minutes of an inquiry and calling back 30 minutes later. Velocify research also reports that responding within 1 minute significantly improves the meeting-conversion rate. In reality, however, a study (2026 Blazeo survey) shows the average B2B company's lead response time exceeds 42 hours, so improving speed tends to be an immediate lever for raising the meeting-conversion rate.",
      "When the meeting-conversion rate is low, the causes can be broadly classified into three. First, a \"lead-quality problem\"—many off-target leads are flowing in. Second, \"insufficient nurturing\"—continuous information provision to early-stage leads is lacking, and they drop off before their interest rises. Third, \"delayed or missed follow-up\"—relying on reps' manual handling creates inconsistency. Effective improvement approaches include certainty screening via pre-information gathering such as BANT, staged nurturing using MA tools, and systematizing inside sales to automate contact timing.",
      "Note that in research on B2B buying behavior (Gartner / Forrester studies), buyers are said to complete most of the buyer journey through self-research before contacting a sales rep, so the self-service experience on the website tends to be directly tied to the meeting-conversion rate. Meeton ai, provided by DynaMeet, has four modules (Meeton Calendar / Chat / Library / Email) that, as an AI SDR resident on the website, autonomously handle conversation with visitors, content recommendation, meeting booking, and follow-up, and is used to simultaneously improve both speed and zero-misses from inquiry to meeting conversion.",
    ],
    faq: [
      {
        q: "Please tell me the formula for the meeting-conversion rate.",
        a: "Meeting-conversion rate (%) = number of converted meetings ÷ total leads × 100. Standardizing the definition of \"lead\" used as the denominator (all inquiries, or MQL only, etc.) internally is a prerequisite for accurate measurement.",
      },
      {
        q: "What is the industry average meeting-conversion rate?",
        a: "It varies widely by industry, channel, and product, so it cannot be stated uniformly, but benchmarks often cited in Japan's B2B space are around 35–40% for inbound leads and around 10–15% for outbound cold leads. The most practical approach is to run a PDCA cycle based on your own past results.",
      },
      {
        q: "How does the meeting-conversion rate differ from the win (close) rate?",
        a: "The meeting-conversion rate shows the conversion efficiency of \"lead → meeting,\" while the win rate (close rate) shows the conversion efficiency of \"meeting → contract.\" The former is often used to evaluate marketing / inside sales and the latter to evaluate field sales, and combining both lets you judge the overall health of the pipeline.",
      },
    ],
    related: ["ai-sdr", "mql-sql", "inbound-sales"],
    metaTitle: "What is the meeting-conversion rate?｜Meeton ai",
    metaDescription:
      "The meeting-conversion rate is a sales KPI showing the proportion of acquired leads that actually advanced to a meeting. We clearly explain the formula, industry averages, the inbound vs. outbound difference, and its relationship with Speed to Lead—essentials for B2B sales and marketing.",
  },
  "inside-sales": {
    slug: "inside-sales",
    term: "Inside sales",
    cluster: "calendar",
    shortDef:
      "Inside sales is a sales method (and a specialized function) that uses non-face-to-face channels such as phone, email, and online meetings to handle everything from nurturing prospects to creating meetings. Divided in labor from field sales, it nurtures the leads marketing acquires into high-certainty opportunities and hands them off to closers in a state where the win probability has been raised.",
    body: [
      "Inside sales is a method of conducting sales activities non-face-to-face from an office, home, or elsewhere, also called \"in-house sales.\" In Japan it was initially often perceived as an extension of telemarketing, but it is now positioned as a strategic function within \"The Model\"–type divided organizations. It receives the leads generated by marketing, nurtures the relationship while confirming the prospect's issues, budget, and decision-making process non-face-to-face, and hands them off to field sales or a contract owner once the likelihood of meeting conversion rises. Because it needs no visit cost, its biggest productivity advantage is that the number of leads one person can handle is far higher than in field sales.",
      "The area inside sales covers is often divided into \"SDR (Sales Development Representative)\" and \"BDR (Business Development Representative)\" by the lead's inflow route. SDRs receive inbound leads such as web forms and content downloads and aim for meeting conversion mainly targeting SMBs—the \"response type.\" BDRs proactively approach based on targeting lists and create new touchpoints with large enterprises—the \"new-prospecting type.\" Because both presuppose high-frequency contact without face-to-face travel, integration with CRM and sales-engagement tools is a practical prerequisite.",
      "Behind the attention to inside sales is the change in buying behavior. It is widely known from a CEB (now Gartner) study that B2B buyers first contact a sales rep at a stage where the buying process is about 57–70% complete, and subsequent studies show the trend that \"time spent in direct interaction with sales is only 17% of the entire purchase\" (Gartner) is strengthening. Therefore, the role of inside sales—continuing to maintain touchpoints via email and content while the buyer self-learns—is emphasized as directly tied to the win rate. Also, a large-scale study by the MIT Sloan School of Management and InsideSales.com (2007, published in HBR 2011) reports that contacting an inbound lead within 5 minutes makes the contact rate about 100x and the meeting-conversion rate about 21x higher than contacting 30 minutes later, making \"Speed to Lead\" one of the most important KPIs in inside sales.",
      "With the spread of AI and automation, the practice of inside sales is changing rapidly from 2024 to 2026. Instant lead notification, automatic follow-up emails, and automated meeting coordination are becoming standardized, and the area inside-sales reps should focus on is shifting to \"quality of discovery\" and \"timing optimization.\" Meeton ai is an AI SDR Platform that runs on the website, and through four modules—chat handling (Meeton Chat), content recommendation (Meeton Library), meeting booking (Meeton Calendar), and continuous follow-up (Meeton Email)—it is used to automate the initial-contact phase of inside sales 24/7/365.",
    ],
    faq: [
      {
        q: "What's the difference between inside sales and telemarketing?",
        a: "Telemarketing is a single-function activity whose main purpose is to win appointments via calls, whereas inside sales is a strategic function that handles multiple processes such as lead nurturing, issue discovery, meeting conversion, and information provision. Also, while telemarketing emphasizes \"quantity\" by churning through numbers, inside sales emphasizes optimizing \"quality\" and \"timing\" based on CRM data and behavior history.",
      },
      {
        q: "How should I divide roles with field sales?",
        a: "A common division pattern is for inside sales to handle \"lead nurturing through the meeting-conversion (SQL) decision\" and for field sales to handle \"proposal through closing.\" Quantifying the handoff criteria (budget, issue, decision timing, certainty) with a framework such as \"BANT\" stabilizes the quality and speed of the handoff.",
      },
      {
        q: "What are the main KPIs for inside sales?",
        a: "Commonly set KPIs include contact rate (connect rate), meeting-conversion rate (SQL conversion rate), lead time to first contact (Speed to Lead), monthly meetings per rep, and nurturing continuation rate. To balance the volume of lead inflow and the quality of meeting conversion, it is common to set a combination of volume metrics and quality metrics.",
      },
    ],
    related: ["speed-to-lead", "ai-sdr", "shodanka-ritsu"],
    metaTitle: "What is inside sales?｜Meeton ai",
    metaDescription:
      "Inside sales is a sales method that uses non-face-to-face channels such as phone, email, and web meetings to handle everything from nurturing prospects to creating meetings. We clearly explain the SDR/BDR difference, Speed to Lead, and changes in the buying process—essentials for B2B sales professionals.",
  },
  "lead-nurturing": {
    slug: "lead-nurturing",
    term: "Lead nurturing",
    cluster: "email",
    shortDef:
      "Lead nurturing is a marketing activity that continuously provides information and communicates with acquired prospects (leads) until their buying intent rises, nurturing them toward meeting conversion and closing. Derived from \"nurture,\" its purpose is to not abandon latent prospects who do not buy immediately, but to maintain the relationship and hand them off to sales at the right time.",
    body: [
      "In B2B buying behavior, prospects are said to have already self-completed 57–70% of the buying process before they first contact a sales rep (Forrester/CEB studies). In other words, leads a company judges \"too early\" are advancing comparison and consideration beneath the surface, and abandoning them risks losing them to competitors. Lead nurturing fills this gap—a mechanism that keeps delivering value even during the period when leads are \"researching on their own.\"",
      "Representative measures span a wide range: email sequences (step emails), webinars, white-paper offers, case-study article distribution, retargeting ads, and more. The common point is \"content design matched to the buying stage\"—staging it gradually, such as issue-raising content in the awareness phase, comparison / ROI appeals in the consideration phase, and case studies / trial guidance in the decision phase. There is data that companies that design nurturing appropriately can increase meeting-converted leads by 50%+ while reducing acquisition cost by about 33% compared with companies that do not (Forrester Research).",
      "As a premise for nurturing to work, \"Speed to Lead (initial response speed)\" cannot be overlooked either. An MIT/InsideSales.com study shows that responding within 5 minutes of an inquiry versus 30 minutes later can produce up to a 100x difference in contact success rate. Nurturing is often discussed in the context of \"long-term cultivation,\" but immediate response to hot leads and mid-to-long-term follow-up are two wheels of the same cart—results are hard to achieve if either is missing.",
      "Meeton ai (an AI SDR Platform) autonomously handles conversation with website visitors, content recommendation, meeting booking, and follow-up emails across four modules (Meeton Calendar / Chat / Library / Email). By having AI handle the initial follow-up and continuous nurturing that traditionally relied on people, 24/7, it is designed to cover both the Speed-to-Lead challenge and lead abandonment. After understanding lead nurturing as a term, use this as a reference when considering how to automate its implementation.",
    ],
    faq: [
      {
        q: "What's the difference between lead nurturing and lead generation?",
        a: "Lead generation is the \"activity of newly acquiring prospects\"—ads, SEO, trade shows, etc. Lead nurturing is the downstream process, the \"activity of warming up acquired leads and raising their buying intent.\" The two are not independent measures but are generally designed as a continuous process within overall demand generation.",
      },
      {
        q: "What types of content are best for nurturing?",
        a: "It differs by buying stage. Blog articles, videos, and webinars are effective for the awareness / issue-understanding phase; white papers, case-study materials, and ROI calculation tools tend to function well in the comparison / consideration phase. In the decision phase, free trials, demo guidance, and customer-story interviews push meeting conversion forward. As a channel, email remains the mainstay—there is a report that the average CTR of nurturing emails is about 2.7x that of general emails (Sender.net survey).",
      },
      {
        q: "Can you start lead nurturing without an MA tool?",
        a: "At a small scale, yes. You can achieve basic nurturing just by managing leads by stage in a CRM, building a content calendar in a spreadsheet, and setting up sequences with an email tool (such as Mailchimp or HubSpot's free plan). However, as the number of leads grows, scoring and behavior-triggered delivery can no longer keep up manually, so once you exceed a certain scale, consider introducing an MA tool or an AI agent.",
      },
    ],
    related: ["sales-engagement", "ai-sdr", "shodanka-ritsu"],
    metaTitle: "What is lead nurturing?｜Meeton ai",
    metaDescription:
      "Lead nurturing is a cultivation activity that provides continuous information to acquired prospects to raise their buying intent. 57–70% of B2B buyers decide through self-research, and abandoning them lets them flow to competitors. We explain methods, FAQ, and tool-selection points.",
  },
  "mql-sql": {
    slug: "mql-sql",
    term: "MQL / SQL",
    cluster: "ai-sdr",
    shortDef:
      "An MQL (Marketing Qualified Lead) is a prospect the marketing team has judged \"worth handing off to sales,\" and an SQL (Sales Qualified Lead) is a lead the sales team has further judged \"can be converted into a meeting.\" The two are \"stages\" where the same lead's label changes as it advances through the buying process, and they function as a shared definition for articulating the collaboration criteria between marketing and sales.",
    body: [
      "An MQL (Marketing Qualified Lead) refers to a prospect that meets the scoring criteria set by the marketing team. Typical judgment materials are a combination of behavior data—viewing specific pages, downloading content, attending webinars, email open rates—plus attribute information such as industry, company size, and job title. Many companies adopt a staged funnel where a lead starting as a MAL (Marketing Accepted Lead) is promoted to MQL through nurturing. What matters is that the definition of MQL is something each company designs to fit its own product, sales cycle, and organizational structure—there is no industry-wide fixed value.",
      "An SQL (Sales Qualified Lead) refers to a lead that the sales team (or inside sales) receiving the MQL has scrutinized with criteria such as BANT (Budget / Authority / Need / Timeline) and judged \"can advance to an appointment / meeting.\" In Japanese B2B organizations, there are cases that set four stages—MAL → MQL → SAL (Sales Accepted Lead) → SQL—and cases that omit SAL and manage in two stages, MQL → SQL. Setting an SAL lets you separate the \"marketing send-off criteria\" from the \"inside-sales acceptance criteria,\" preventing the back-and-forth pushing of low-quality leads and making cross-team consensus easier.",
      "The biggest value the MQL/SQL distinction brings to an organization is the \"clarification of handoff criteria\" that lets marketing and sales speak the same language. If this definition is operated while ambiguous, sales become dissatisfied that \"the leads marketing sends are low quality\" and marketing feels that \"sales don't follow up properly\"—the typical siloing occurs. Also, according to studies such as Forrester, 57–70% of B2B buyers have already finished gathering information before contacting a sales rep, so incorporating lead signals at that stage as MQL criteria has become indispensable in modern inbound marketing.",
      "The MQL-to-SQL conversion rate varies greatly by industry and channel, but around 12–21% is widely cited as a reference value for B2B SaaS (First Page Sage, 2026). The speed of first contact with a lead is also directly tied to the conversion rate. According to multiple studies such as the MIT Lead Response Management Study, there is a large difference in contact success rate between responding within 5 minutes of an inquiry and responding 30 minutes or later. Meeton ai's AI SDR modules (Meeton Chat / Calendar) are designed as one response to this \"Speed to Lead\" challenge, and are used to automate conversation, content recommendation, and meeting booking the moment an MQL is detected on the website.",
    ],
    faq: [
      {
        q: "Who decides MQL and SQL?",
        a: "MQL is judged by the marketing team based on the scoring and behavior criteria it sets, and SQL is judged by the sales team (or inside sales) from the perspective of BANT and meeting feasibility. What matters is documenting a definition both teams have agreed on and reviewing it periodically, which prevents misalignment between organizations.",
      },
      {
        q: "How should I set the MQL / SQL criteria?",
        a: "The starting point is to analyze your own past deal data and extract the behavior patterns and attributes common to leads that closed. In a scoring model, it is common to assign points to page views, form submissions, content downloads, etc., and define leads exceeding a threshold as MQLs. The initial values can be provisional; an agile operation that adjusts quarterly based on actual data is recommended.",
      },
      {
        q: "How do I promote an MQL to an SQL?",
        a: "A combination of lead nurturing (continuous information provision via email and content) and outreach by inside sales at the right timing is effective. In particular, the speed of first contact right after an inquiry or behavior signal occurs is said to affect the contact rate and meeting-conversion rate, so building a system to approach \"while the lead's heat is high\" is the key to improving the conversion rate.",
      },
    ],
    related: ["ai-sdr", "shodanka-ritsu", "inbound-sales"],
    metaTitle: "What are MQL / SQL?｜Meeton ai",
    metaDescription:
      "An MQL (Marketing Qualified Lead) is a lead marketing judged \"worth handing to sales,\" and an SQL (Sales Qualified Lead) is a lead sales judged \"can be converted into a meeting.\" We explain the differences, judgment criteria, and conversion-rate benchmarks from a B2B practitioner's perspective.",
  },
  "inbound-sales": {
    slug: "inbound-sales",
    term: "Inbound sales",
    cluster: "ai-sdr",
    shortDef:
      "Inbound sales is a sales method that designs a flow in which prospects contact and inquire with a company on their own through content or ads, and then connects that interest to meetings and deals. It is a concept paired with outbound sales—where the company unilaterally approaches via telemarketing or cold visits—and, against the backdrop of growing self-learning behavior by customers due to digitalization, its adoption is advancing in Japan's B2B market as well.",
    body: [
      "The biggest difference between inbound sales and outbound sales is \"who moves first.\" Outbound sales is a proactive approach where reps call and email a target list, whereas inbound sales is where the prospect contacts the company through searches, content downloads, webinar attendance, and so on. In B2B purchasing, as shown by studies indicating buyers self-complete about 57–70% of the buying process before they first contact a sales rep (CEB/Gartner research reports 57%, Forrester research reports 70%), customers talk to sales after already finishing a considerable amount of information gathering. Inbound sales aims to raise the warmth at the first contact by maintaining a presence with quality content during this \"self-learning phase before contact.\"",
      "It helps to organize the difference from outbound sales axis by axis. [Who moves first] Outbound: the sales side; inbound: the prospect. [Main channels] Outbound uses cold calls, cold visits, and cold email; inbound uses SEO articles, white papers, webinars, web inquiries, and chat. [Lead warmth] Outbound starts from a state where the prospect's interest is unknown, so it tends to be lower; inbound tends to be warmer because the prospect reaches out voluntarily. [Meeting-conversion tendency] Voluntary inbound leads generally convert to meetings at a higher rate (around 20% is one benchmark for the industry-average meeting-conversion rate via B2B web inquiries). [Time to results] Outbound can start hitting the same day, whereas inbound requires a run-up of several months until content assets mature. [Cost structure] Outbound's labor and calling costs scale with volume, while inbound's up-front content investment becomes an asset and is more efficient over the mid-to-long term. [Best fit] Outbound suits pinpoint targeting of specific companies; inbound suits continuously collecting leads from a broad latent audience. In practice, a hybrid that combines the two is mainstream.",
      "It is also worth organizing the merits and demerits of inbound sales compared with outbound sales. Merits include: (1) leads that voluntarily show interest tend to have higher win rates, (2) content assets keep generating inflow over the long term, so mid-to-long-term cost efficiency is high, and (3) it is less likely to give customers the impression of being \"sold to.\" On the other hand, you must keep in mind demerits: (1) it takes an investment period on the order of several months until search inflow and white-paper downloads stabilize, (2) it is hard to narrow down to specific companies / targets you want to appeal to, and (3) an overly passive design risks missing harvesting opportunities. In practice, many companies adopt a hybrid strategy that combines outbound-style follow-up for leads nurtured via inbound.",
      "The main measures of inbound sales are broadly divided into two stages: \"inflow acquisition\" and \"lead nurturing / conversion.\" For inflow acquisition, representative measures are SEO-conscious owned-media articles, white papers, webinars, social posting, and press releases. In the lead nurturing / conversion stage, the keys are email sequences and lead scoring using MA tools, and rapid follow-up after an inquiry. A Harvard Business Review study (2011) reports that companies responding to a web inquiry within 1 hour were about 7x more likely to convert the lead into a meeting than companies responding after 1 hour (so-called \"Speed to Lead\"). Alongside enriching inflow measures, organizing the response speed and response quality after an inquiry is directly tied to results.",
      "Something easily overlooked in inbound sales is that \"the speed of the initial response (Speed to Lead) determines the meeting-conversion rate.\" An inbound lead who inquired on their own is in the \"golden window\" of highest buying intent at the very moment of contact. Yet many B2B companies rely on manual handling by reps, and it is not unusual for a reply to take hours to tens of hours—during which the lead's warmth cools and competitors get ahead. The meeting-conversion rate via B2B web inquiries is often benchmarked at around 20% on industry average, but simply speeding the initial response down to seconds can change that number dramatically. In fact, EdulinX—which introduced a mechanism where AI on the website responds in 5 seconds and never misses leads 24/7/365—achieved a meeting-conversion rate of over 60%. The details of the initial response are covered in the related term \"Speed to Lead,\" and by combining it with Meeton Calendar, which automates everything from conversation to meeting booking, you can reach meeting conversion while an inbound lead is still hot.",
      "It is good to design the practical steps for converting inbound leads into meetings in roughly five stages. First, \"instant response\"—automatically give a first reply the moment an inquiry, chat, or content request arises (with a chat you can install in about 5 minutes via one line of JavaScript, you won't miss inflow outside business hours). Second, \"discovery and qualification\"—confirm the issue, budget, and level of consideration through conversation using a framework such as BANT, and identify high-certainty leads. Third, \"recommending relevant content\"—present case studies and service materials matched to the prospect's interest to support their comparison. Fourth, \"instantly offering a meeting slot\"—while interest is high, present open slots straight from the calendar and complete the booking on the spot. Fifth, \"following up unbooked leads\"—continue 1:1 follow-up according to behavioral signals even for leads who didn't book right away. Whether you can keep this five-step cycle running 24/7/365 without depending on manual capacity is what separates inbound-sales outcomes.",
      "In the context of strengthening the inbound flow on a website, the use of chatbots and conversational AI has been attracting attention in recent years. By setting up a mechanism that not only has an inquiry form but also answers questions in real time according to the visitor's interest, recommends content, and completes meeting booking, you can expect effects such as \"not missing nighttime / holiday inflow\" and \"completing initial discovery even during hours when no sales rep is present.\" Meeton ai (DynaMeet) is an AI SDR platform designed to automate this inbound flow, and its four modules—conversation, content recommendation, scheduling, and follow-up (Meeton Calendar / Chat / Library / Email)—can be embedded into a website. Returning to the perspective of a term explanation, it is important to understand that inbound sales is not merely \"waiting sales\" but a systematic sales model that demands the combined strength of content investment, flow design, response speed, and nurturing logic.",
    ],
    faq: [
      {
        q: "What is inbound sales?",
        a: "Inbound sales is a sales method that designs a flow in which prospects contact a company on their own—through searches, content downloads, webinar attendance, and so on—and converts that interest into meetings and deals. It is a concept paired with outbound sales, where the company approaches via calls or visits. The basics are to maintain a presence with quality content during the \"self-learning phase before contact,\" then convert to meetings through a rapid initial response after an inquiry.",
      },
      {
        q: "What is the difference between inbound sales and outbound sales?",
        a: "The biggest difference is \"who moves first.\" Outbound sales is a proactive approach where reps call and email a target list; it can pinpoint specific companies and start the same day, but begins from a state where the lead's warmth is unknown. Inbound sales, where prospects reach out voluntarily, tends to have warmer leads and higher meeting-conversion rates, but requires a run-up of several months until content assets mature. In practice, a hybrid that combines the two is mainstream.",
      },
      {
        q: "How can I raise the meeting-conversion rate in inbound sales?",
        a: "The key is the speed of the initial response (Speed to Lead). An inbound lead who inquired on their own has the highest buying intent at the moment of contact, and the more the initial response is delayed, the more their warmth cools. The meeting-conversion rate via B2B web inquiries is often benchmarked at around 20% on industry average, but by responding instantly right after an inquiry and completing conversation, content recommendation, and meeting booking on the spot, it can be raised significantly. EdulinX, which introduced AI that responds in 5 seconds and never misses leads 24/7/365, achieved a meeting-conversion rate of over 60%.",
      },
      {
        q: "What's the difference between inbound sales and inbound marketing?",
        a: "Inbound marketing refers to the overall \"inflow acquisition\" activities that attract prospects to your company through SEO, content, social, and so on. Inbound sales refers to the \"sales process\" that converts the leads generated by that inflow into meetings and deals. A common division has marketing create leads and sales handle closing, but at SMBs they are often operated together.",
      },
      {
        q: "Where should I start to begin inbound sales?",
        a: "The standard approach is to first organize the persona and issues—\"whose what problem do you solve\"—and from there decide the priority of content such as SEO articles and white papers. At the same time, it is important to prepare the post-inflow CTA (content download / inquiry form / chat) and the post-inquiry response flow (auto-reply / rep assignment / follow-up email); even if you only increase inflow, the meeting-conversion rate will not rise if response speed or quality is low.",
      },
    ],
    related: ["ai-sdr", "shodanka-ritsu", "speed-to-lead", "mql-sql"],
    metaTitle: "What is Inbound Sales? Meaning, vs. Outbound & Conversion Tips｜Meeton ai",
    metaDescription:
      "Inbound sales is a sales method that designs a flow in which prospects search and inquire on their own, then connects this to meetings and deals. We clearly explain the difference from outbound, an axis-by-axis comparison, and practical steps to raise conversion with Speed to Lead—for B2B professionals.",
  },
  "sales-engagement": {
    slug: "sales-engagement",
    term: "Sales engagement",
    cluster: "email",
    shortDef:
      "Sales engagement is an umbrella term for the sales strategy and process that systematically manages and optimizes all the communication sales reps conduct with prospects and existing customers across multiple channels—email, phone, social, chat, etc.—simultaneously achieving trust building and improved win certainty. In recent years it often also refers to the software that automates and analyzes this (a sales engagement platform).",
    body: [
      "The biggest reason sales engagement is attracting attention is the change in B2B buying behavior. According to Forrester research, about 70% of B2B buyers have already completed most of the buying process by the time they first contact a sales rep. In other words, customers narrow down candidates via owned media, word of mouth, and comparison sites before sales reach out. In such an environment, \"waiting sales\" lose opportunities, and proactive engagement that delivers valuable information through the right channel at the right time becomes the key to differentiation.",
      "The practical core of sales engagement lies in \"sequences (automation of contact procedures)\" and \"interaction measurement.\" By designing in advance the order and timing of email / phone / social approaches per prospect and tracking reactions (opens, clicks, replies) in real time, you optimize the next action. Also, a joint study by Harvard Business Review and MIT showed that the meeting-conversion rate when making first contact within 5 minutes of an inquiry is up to 21x that when contacting 30 minutes later, making it clear that Speed to Lead (initial speed) greatly affects engagement quality.",
      "It is also worth grasping the difference from CRM / SFA. A CRM's main purpose is accumulating and managing customer information, and SFA specializes in visualizing and managing the progress of the sales process. By contrast, sales engagement focuses on \"actual communication execution and effect measurement\" and generally functions complementarily in coordination with CRM / SFA. It is also easily confused with sales enablement, but whereas enablement is \"developing reps / strengthening organizational capability (internal-facing),\" sales engagement is an \"activity that raises the quality and quantity of the touchpoints with customers themselves (external-facing).\"",
      "With the evolution of AI, sales engagement is evolving from the traditional \"bulk email + CRM logging\" to an AI-agent type that autonomously executes conversation, content recommendation, booking, and follow-up. Meeton ai is an AI SDR platform that plays this role on the website, designed so that four modules—Meeton Chat (conversation), Calendar (meeting booking), Library (content recommendation), and Email (follow-up)—work together to execute sales engagement 24/7 unattended.",
    ],
    faq: [
      {
        q: "What's the difference between sales engagement and sales enablement?",
        a: "Sales engagement is an \"external-facing activity that raises the quality and quantity of touchpoints with customers,\" and sales enablement is an \"internal-facing activity that develops reps' skills, knowledge, and tools.\" The former centers on communication execution, the latter on organization building, and the two are complementary.",
      },
      {
        q: "How does a sales engagement platform differ from a CRM?",
        a: "A CRM's main purpose is recording and managing customer information, whereas a sales engagement platform specializes in actual communication execution across email, phone, and social, and in reaction measurement (open rate, reply rate, etc.). In many cases, the two are used in coordination.",
      },
      {
        q: "What improves when you introduce sales engagement?",
        a: "There are three main improvements: (1) preventing missed follow-ups via sequence automation, (2) optimizing messages and timing based on reaction data, and (3) improving the initial response speed (Speed to Lead) to inquiries. When these combine, they tend to lead to improvements in the meeting-conversion rate and the win rate.",
      },
    ],
    related: ["lead-nurturing", "ai-sdr", "shodanka-ritsu"],
    metaTitle: "What is sales engagement?｜Meeton ai",
    metaDescription:
      "Sales engagement is an umbrella term for a sales strategy that systematically manages and optimizes customer communication across multiple channels—email, phone, social, etc. We clearly explain the differences from CRM, SFA, and sales enablement, and how to use it in B2B sales.",
  },
  "web-sekkyaku": {
    slug: "web-sekkyaku",
    term: "Web engagement (online customer service)",
    cluster: "chat",
    shortDef:
      "Web engagement is an umbrella term for measures that, through chatbots, popups, live chat, and the like, interact with and guide users who visit a website—either in real time or autonomously—to raise conversions and customer satisfaction. It is easy to grasp as recreating physical-store customer service online, and in recent years, with the rise of AI, it has rapidly spread in the B2B domain as well.",
    body: [
      "Web engagement is an umbrella term for measures that proactively act on a website according to user behavior—providing information, hearing out issues, and guiding to the next action. The main means are classified into three types: popup type (showing appeal banners linked to browsing behavior), chat type (a bot or human operator responding to questions), and composite type (a hybrid combining the two). Adoption preceded in B2C, but it is now advancing on B2B sites too.",
      "Behind why web engagement is valued in B2B is the change in buying behavior. According to a Gartner survey of 646 B2B buyers conducted in August–September 2025 (published March 2026), 67% of B2B buyers responded that they prefer a buying experience without a sales rep. In other words, many prospects nearly complete information gathering and comparison on the website before contacting sales. Whether you can answer questions in real time at this stage and present appropriate content or meeting slots becomes a point that determines the meeting-conversion rate.",
      "The effects you can expect from web engagement are mainly improved CVR (conversion rate), churn prevention, and reduced sales workload. With a chatbot responding 24/7, you can accept and not miss inquiries even outside business hours. On the other hand, note that effects tend to plateau if you neglect the post-introduction operational design (scenario improvement, A/B testing, PDCA). When selecting a tool, it is recommended to check whether it has effect-measurement functions and whether it can integrate with CRM / MA.",
      "With the evolution of AI, web engagement is shifting from \"scenario-type chatbots\" to \"autonomous AI agents.\" Traditional scenario types could only respond within the range of pre-assumed questions, but autonomous types using generative AI have become able to understand context and respond flexibly, consistently automating content recommendation, meeting booking, and follow-up. Meeton ai is an AI SDR platform that realizes such autonomous web engagement for B2B sites, composed of four modules—conversation, content recommendation, booking, and follow-up (Meeton Calendar / Chat / Library / Email).",
    ],
    faq: [
      {
        q: "What's the difference between a web engagement tool and a chatbot?",
        a: "A chatbot is one kind of web engagement tool. A web engagement tool is a broad concept including popups, live chat, recommendations, and more, while a chatbot refers to the function within it specialized in conversational auto-response. In recent years chatbots often play the central role in web engagement, but forms that use only popups are also included in web engagement.",
      },
      {
        q: "Is web engagement really effective in B2B?",
        a: "According to Gartner (published March 2026), 67% of B2B buyers prefer an experience without a sales rep, so touchpoints on the website have become decisively important in B2B too. Case studies at manufacturing, HR, and IT SaaS companies report effects such as increased inquiries and reduced sales workload. However, the magnitude of the effect varies greatly with the site's traffic volume, scenario design quality, and continuous improvement.",
      },
      {
        q: "What are the main criteria when choosing a web engagement tool?",
        a: "The main criteria are five points: (1) response format (popup / chat / composite), (2) AI / scenario flexibility, (3) whether it can integrate with CRM / MA, (4) whether it has effect-measurement / A/B-testing functions, and (5) operating cost (initial fee / monthly / internal labor). For B2B sites, whether human handling is available and integration with meeting-booking functions are also important selection points.",
      },
    ],
    related: ["ai-sdr", "shodanka-ritsu", "speed-to-lead"],
    metaTitle: "What is web engagement?｜Meeton ai",
    metaDescription:
      "Web engagement is an umbrella term for measures—chatbots, popups, etc.—that act on website visitors in real time to raise CVR and the meeting-conversion rate. We clearly explain the background of B2B use, types and selection of tools, and the latest trend toward autonomous AI.",
  },
  "document-open-rate": {
    slug: "document-open-rate",
    term: "Document open rate",
    cluster: "library",
    shortDef:
      "Document open rate is a metric indicating the proportion of documents—such as proposals and service materials—sent by a sales rep or campaign that recipients actually opened. Distinguished from email open rate, by visualizing \"whether they touched the content,\" it is used as a basis for judging a prospect's degree of buying interest and the appropriate timing for follow-up.",
    body: [
      "Document open rate is a metric that grasps numerically \"whether a sent document was viewed.\" The formula is expressed as \"number of documents opened ÷ number of documents sent × 100,\" measured by the document-tracking functions adopted by sales-enablement tools such as DocSend, HubSpot Sales, and Highspot. Whereas email open rate measures whether an email was opened, document open rate differs in that it measures \"whether the attached or linked document itself was viewed.\" Because you can also obtain incidental data such as viewing time, viewed pages, and viewing device, deeper engagement analysis than a simple open/no-open is possible.",
      "Behind why document open rate is valued is the change in B2B buying behavior. A CEB (now Gartner) study reports that about 57% of the buying process is self-completed by the time B2B buyers first contact a sales rep, and a Forrester study (2019) presents the view that this proportion reaches 70%. In other words, prospects finish a considerable amount of information gathering and comparison before dialogue with sales begins. In this situation, grasping \"when, up to which page, and for how long\" a sent document was viewed becomes a clue to estimating the prospect's interest phase and discerning the optimal contact timing.",
      "Document open rate is used on both fronts of hot-lead judgment and follow-up speed. Approaching right after detecting a viewing signal after sending a document overlaps with the concept of Speed to Lead mentioned by Harvard Business Review. That study reports that contacting a lead within 5 minutes of its creation makes the connect probability 100x and the qualification probability 21x higher than contacting 30 minutes later. By designing a mechanism that \"contacts right after a document is opened,\" starting from document open rate, you can implement this effect on the sales floor. Integrating with MA tools and CRM also makes it possible to automate it as one element of scoring.",
      "Meeton ai's Meeton Library module is designed so that an AI agent placed on the website recommends content matched to the visitor's interest and, based on its viewing signals, automatically hands off to the subsequent conversation / booking / follow-up flow. By incorporating engagement data such as open rate into pipeline management—rather than ending with \"sent the document and done\"—it aims for meeting conversion that does not miss the timing.",
    ],
    faq: [
      {
        q: "What's the difference between document open rate and email open rate?",
        a: "Email open rate measures whether the email body was opened, while document open rate measures whether the document—proposal, service material, etc.—attached to or linked in the email was actually viewed. Document open rate more directly indicates \"contact with the content,\" so it is considered to more accurately reflect the degree of buying interest.",
      },
      {
        q: "What is a guideline (average) for document open rate?",
        a: "A cross-industry standard benchmark for document open rate is not yet established. As a reference, however, a report from DocSend analyzing 34M+ content interactions yields data such as the average completion rate of proposals and time-of-day patterns. Because it is a different metric from the actual state of domestic B2B email open rates (an IDEATECH survey finds 11–30% is most common), it is practical to target relative improvement based on your own past sending results.",
      },
      {
        q: "How can I raise the document open rate?",
        a: "There are three main approaches. (1) Sending timing: send when interest is high, such as right after a meeting or inquiry. (2) The document itself: state the value clearly on the opening page and reduce drop-off by limiting the number of pages. (3) Notification settings: use a tracking tool that lets you receive viewing signals instantly, and follow up right after an open to raise the conversion rate to the next touchpoint.",
      },
    ],
    related: ["ai-sdr", "shodanka-ritsu", "speed-to-lead"],
    metaTitle: "What is document open rate?｜Meeton ai",
    metaDescription:
      "Document open rate is a B2B sales metric showing the proportion of sent proposals and sales materials that were actually viewed. It is used to judge hot leads and optimize follow-up timing, and is treated separately from email open rate. We explain the definition, formula, and how to use it.",
  },
  "bant": {
    slug: "bant",
    term: "BANT",
    cluster: "ai-sdr",
    shortDef:
      "BANT is a discovery framework for judging whether a lead can be converted into a meeting in B2B sales, combining the initials of four elements: Budget, Authority, Need, and Timeline. Said to have been systematized by IBM in the 1950s, it has taken hold as a basic qualification requirement used widely from inside sales to field sales.",
    body: [
      "BANT refers to four elements: \"Budget,\" \"Authority,\" \"Need,\" and \"Timeline.\" Budget is the scale of budget that can be allocated to your product / service; Authority is the degree of access to the person with final contract decision authority; Need is the fit between the customer's issues and your solution; Timeline is the target timing for introduction / starting consideration. The common operation is to prioritize for meeting conversion the leads in which all four elements are present, treating them as \"promising opportunities that meet the BANT conditions.\"",
      "While BANT is simple, it is sometimes pointed out to diverge from modern B2B buying behavior. Studies by Forrester, 6sense, and others report that by the time B2B buyers first contact a sales rep, 57–70% of the buying consideration is already complete. In other words, by the time the opportunity to ask BANT questions arrives, much of the customer's decision-making is often already self-completed. For this reason, a growing number of companies use BANT not as a \"question list to extract everything at once in conversation\" but as a checklist for gathering information gradually across multiple touchpoints.",
      "How quickly and accurately you can grasp BANT information is also an important competitive factor. A study cited by Harvard Business Review finds that companies responding within 1 hour of an inquiry were 7x more likely to have a meaningful conversation with a decision-maker than companies that waited more than 1 hour (Lead Response Management Study). In that response speed determines the very opportunity to confirm BANT, \"Speed to Lead\" can be called a prerequisite for using BANT.",
      "In Meeton ai (an AI SDR Platform), a chatbot placed on the website (Meeton Chat) collects, in real time through conversation with visitors, information corresponding to Budget, Need, and Timeline; Meeton Calendar instantly presents meeting slots to promising leads; and Meeton Email automates subsequent follow-up. By having the tool gradually supplement each BANT element, it aims to create an environment where sales reps can focus on the leads truly worth converting into meetings.",
    ],
    faq: [
      {
        q: "How does BANT differ from CHAMP or MEDDIC?",
        a: "While BANT centers on budget, authority, need, and timing, CHAMP is a customer-perspective variant that prioritizes Challenges, and MEDDIC is an enterprise-oriented extension that adds quantitative economic impact (Metrics) and identification of the decision process. It is common to use them differently depending on the complexity of your product and the length of the sales cycle.",
      },
      {
        q: "Is it more effective to confirm BANT by phone or email?",
        a: "There is no fixed right answer; it varies with deal price and depth of relationship. A hybrid operation is often adopted in practice—grasping the general situation in a first call or a follow-up email after a webinar, and supplementing Budget and Timeline with a pre-meeting survey or a form at content download.",
      },
      {
        q: "Is it OK to convert to a meeting even if not all four BANT elements are present?",
        a: "It is entirely possible to judge that you should convert even if some elements are missing. In particular, when Need is clear and Timeline is short, budget and the decision route can be built up through the meeting. BANT is not a rule of \"don't move unless all items are present\" but is realistically used as judgment material for deciding priority and the next action.",
      },
    ],
    related: ["ai-sdr", "shodanka-ritsu", "mql-sql"],
    metaTitle: "What is BANT?｜Meeton ai",
    metaDescription:
      "BANT is a standard B2B sales framework that evaluates leads with four elements: Budget, Authority, Need, and Timeline. We clearly explain the meaning, how to use it, and the limits and use points in modern B2B of the method IBM systematized.",
  },
  "plg": {
    slug: "plg",
    term: "PLG (Product-Led Growth)",
    cluster: "ai-sdr",
    shortDef:
      "PLG (Product-Led Growth) is a go-to-market strategy that makes the product itself the main engine of user acquisition, conversion, and expansion—letting users experience value first via a free plan or free trial, with convinced users voluntarily moving to paid. Contrasted with the traditional sales-led (SLG) approach, it is rapidly spreading in the SaaS / B2B software domain.",
    body: [
      "PLG (Product-Led Growth) is a go-to-market strategy that makes \"trying the product\" itself the starting point of customer acquisition. In traditional SLG (sales-led growth), a sales rep conveys the value via demos and proposals before the customer first proceeds to a trial, but in PLG the order is reversed. First, you let users experience the product via a free plan, free trial, or interactive demo, and based on that experience value you prompt upgrades. The fact that not only decision-makers but also front-line users can try it themselves aligns with the change in IT-tool buying behavior. A Forrester study (2019) and a 6sense study (of 900+ B2B buyers) report that about 70% of B2B buyers complete most of the buying process through self-research before contacting sales, and PLG has a high affinity with this \"want to research first\" mindset.",
      "An important concept in realizing PLG is the PQL (Product Qualified Lead). Unlike an MQL (a lead via marketing) or an SQL (a sales-evaluated lead), a PQL evaluates a lead by \"the product-usage behavior itself.\" For example, a user who used a specific feature multiple times during a free trial, or a user who invited team members, qualifies. According to a ProductLed study, companies leveraging PQLs tend to have about a 3x free-to-paid conversion rate compared with those that do not, and the median visitor conversion rate in a freemium model is reported to be about 12% (ProductLed Benchmarks). However, the numbers vary greatly with product complexity and ACV (annual contract value), so it is essential to validate in the context of your own product.",
      "PLG is not suitable for every B2B product. It tends to work especially for products with a relatively low price where the end user can decide on adoption themselves (under $10K ACV is often cited as a guideline). On the other hand, high-priced products requiring agreement among multiple stakeholders, or products that require specialized onboarding, may fit SLG better in some cases. Attracting attention in recent years is the hybrid model called \"PLS (Product-Led Sales),\" a strategy that concentrates sales resources only on accounts with a high likelihood of going enterprise among the users efficiently acquired and screened via PLG. McKinsey analysis also reports that many SaaS companies with over $10M ARR are advancing this shift to PLS.",
      "Interest in PLG is rapidly rising in Japan's B2B market as well. Centered on domestic SaaS companies, the provision of free plans and the development of in-product onboarding are advancing. On the other hand, there are scenes where Japanese business customs (ringi, multiple approvers, vendor-evaluation processes) do not necessarily mesh with PLG's \"try it first\" flow, and it is said that a PLS hybrid often fits the reality better than pure PLG. A design that combines self-experience on the website with rapid sales follow-up for hot leads becomes a realistic approach to practicing PLG in the Japanese market. Note that an AI SDR Platform like Meeton ai is also used in contexts such as autonomously approaching website visitors and automating immediate follow-up for PQLs acquired via PLG.",
    ],
    faq: [
      {
        q: "What's the difference between PLG and SLG?",
        a: "Whereas SLG (sales-led growth) has the order where a sales rep conveys value and then lets the customer trial the product, PLG is the reverse model where you let them experience the product first and then prompt a paid conversion. PLG tends to keep customer acquisition cost (CAC) low, while SLG suits high-priced, complex products. In recent years, a \"PLS (Product-Led Sales)\" hybrid combining the two is becoming mainstream.",
      },
      {
        q: "What is a PQL (Product Qualified Lead)?",
        a: "A PQL is a lead judged to have a high likelihood of paid conversion after actually experiencing the product's value through a free plan or free trial. Its characteristic is scoring based on \"product-usage behavior\" rather than MQL (marketing behavior) or SQL (sales evaluation), making it a central metric in a PLG strategy.",
      },
      {
        q: "Does PLG work in Japanese B2B too?",
        a: "It tends to work for products with a relatively low price that end users can adopt at their own discretion, but pure PLG does not fit well with high-priced products requiring ringi or multiple approvals. Realistically, a \"PLS hybrid\"—drawing interest with a free trial, identifying PQLs, and then having sales intervene—is considered an effective approach in the Japanese market.",
      },
    ],
    related: ["ai-sdr", "shodanka-ritsu", "mql-sql"],
    metaTitle: "What is PLG (Product-Led Growth)?｜Meeton ai",
    metaDescription:
      "PLG (Product-Led Growth) is a go-to-market strategy that makes the product experience itself the main engine of customer acquisition and conversion. Users experience value first via a free plan or free trial and voluntarily move to paid. We clearly explain the difference from SLG, PQL, and how to practice it in Japanese B2B.",
  },
} as Record<string, GlossaryTerm>;

export function getTerm(slug: string): GlossaryTerm | undefined {
  return GLOSSARY[slug];
}
export function getTermEn(slug: string): GlossaryTerm | undefined {
  return GLOSSARY_EN[slug];
}
export function allTermSlugs(): string[] {
  return Object.keys(GLOSSARY);
}
export function allTerms(): GlossaryTerm[] {
  return Object.values(GLOSSARY);
}
export function allTermsEn(): GlossaryTerm[] {
  return Object.values(GLOSSARY_EN);
}
